In [2]:
"""Features Taken
1. 'PERNOTMVIT': Number of Non-Mototrists
2. 'VE_TOTAL': Vehicles Involved in the Crash 
3. 'VE_FORMS', 'PVH_INVL': Add them to get impacted vehicles not in crash
4. 'PERMVIT': Occupants of vehicle crased
5. 'FUNC_SYSNAME': Functional classification of the segment of the trafficway
6. 'HARM_EVNAME': What actually happened
7. 'LGT_CONDNAME': Light Condition
8. 'NOT_HOURNAME', 'NOT_MINNAME': Time at which emergency service was notified
9. 
"""

"Features Taken\n1. 'PERNOTMVIT': Number of Non-Mototrists\n2. 'VE_TOTAL': Vehicles Involved in the Crash \n3. 'VE_FORMS', 'PVH_INVL': Add them to get impacted vehicles not in crash\n4. 'PERMVIT': Occupants of vehicle crased\n5. 'FUNC_SYSNAME': Functional classification of the segment of the trafficway\n6. 'HARM_EVNAME': What actually happened\n7. 'LGT_CONDNAME': Light Condition\n8. 'NOT_HOURNAME', 'NOT_MINNAME': Time at which emergency service was notified\n9. \n"

In [3]:
import pandas as pd
accident = pd.read_csv(r'C:\DATA ANALYSIS AND DATA SCIENCE PROJECTS\Accident Severity Prediction\data\raw data files\accident.csv')
accident.head()

,STATE,STATENAME,ST_CASE,PEDS,PERNOTMVIT,VE_TOTAL,VE_FORMS,PVH_INVL,PERSONS,PERMVIT,...,NOT_MINNAME,ARR_HOUR,ARR_HOURNAME,ARR_MIN,ARR_MINNAME,HOSP_HR,HOSP_HRNAME,HOSP_MN,HOSP_MNNAME,FATALS
0,1,Alabama,10001,0,0,1,1,0,1,1,...,20,22,10:00pm-10:59pm,45,45,88,Not Applicable (Not Transported),88,Not Applicable (Not Transported),1
1,1,Alabama,10002,0,0,1,1,0,1,1,...,8,2,2:00am-2:59am,23,23,88,Not Applicable (Not Transported),88,Not Applicable (Not Transported),1
2,1,Alabama,10003,0,0,1,1,0,1,1,...,48,23,11:00pm-11:59pm,8,8,88,Not Applicable (Not Transported),88,Not Applicable (Not Transported),1
3,1,Alabama,10004,0,0,1,1,0,3,3,...,0,19,7:00pm-7:59pm,44,44,99,Unknown,99,Unknown EMS Hospital Arrival Time,1
4,1,Alabama,10005,0,0,1,1,0,4,4,...,53,15,3:00pm-3:59pm,8,8,99,Unknown,99,Unknown EMS Hospital Arrival Time,1

In [4]:
accident.columns

Index(['STATE', 'STATENAME', 'ST_CASE', 'PEDS', 'PERNOTMVIT', 'VE_TOTAL',
       'VE_FORMS', 'PVH_INVL', 'PERSONS', 'PERMVIT', 'COUNTY', 'COUNTYNAME',
       'CITY', 'CITYNAME', 'MONTH', 'MONTHNAME', 'DAY', 'DAYNAME', 'DAY_WEEK',
       'DAY_WEEKNAME', 'YEAR', 'HOUR', 'HOURNAME', 'MINUTE', 'MINUTENAME',
       'TWAY_ID', 'TWAY_ID2', 'ROUTE', 'ROUTENAME', 'RUR_URB', 'RUR_URBNAME',
       'FUNC_SYS', 'FUNC_SYSNAME', 'RD_OWNER', 'RD_OWNERNAME', 'NHS',
       'NHSNAME', 'SP_JUR', 'SP_JURNAME', 'MILEPT', 'MILEPTNAME', 'LATITUDE',
       'LATITUDENAME', 'LONGITUD', 'LONGITUDNAME', 'HARM_EV', 'HARM_EVNAME',
       'MAN_COLL', 'MAN_COLLNAME', 'RELJCT1', 'RELJCT1NAME', 'RELJCT2',
       'RELJCT2NAME', 'TYP_INT', 'TYP_INTNAME', 'REL_ROAD', 'REL_ROADNAME',
       'WRK_ZONE', 'WRK_ZONENAME', 'LGT_COND', 'LGT_CONDNAME', 'WEATHER',
       'WEATHERNAME', 'SCH_BUS', 'SCH_BUSNAME', 'RAIL', 'RAILNAME', 'NOT_HOUR',
       'NOT_HOURNAME', 'NOT_MIN', 'NOT_MINNAME', 'ARR_HOUR', 'ARR_HOURNAME',
       'ARR_MIN', 'ARR_MINNAME', 'HOSP_HR', 'HOSP_HRNAME', 'HOSP_MN',
       'HOSP_MNNAME', 'FATALS'],
      dtype='object')

In [5]:
columns_to_keep = ['STATE', 'STATENAME', 'ST_CASE', 'PERNOTMVIT', 'VE_TOTAL',
       'VE_FORMS', 'PVH_INVL', 'PERMVIT', 'CITYNAME', 'MONTHNAME', 'DAYNAME',
       'DAY_WEEKNAME', 'HOUR', 'MINUTE', 'RUR_URBNAME', 'FUNC_SYSNAME',
       'NHSNAME', 'LATITUDE', 'LONGITUD', 'HARM_EVNAME', 'TYP_INTNAME', 'LGT_CONDNAME',
       'WEATHERNAME', 'NOT_HOURNAME', 'NOT_MINNAME', 'ARR_HOURNAME', 
       'ARR_MINNAME', 'HOSP_HRNAME', 'HOSP_MNNAME', 'FATALS']

columns_to_drop = ['PEDS', 'PERSONS', 'COUNTY', 'COUNTYNAME',
       'CITY', 'MONTH', 'DAY', 'DAY_WEEK', 'YEAR', 'HOURNAME', 'MINUTENAME',
       'TWAY_ID', 'TWAY_ID2', 'ROUTE', 'ROUTENAME', 'RUR_URB', 'FUNC_SYS', 'RD_OWNER', 
       'RD_OWNERNAME', 'NHS', 'SP_JUR', 'SP_JURNAME', 'MILEPT', 'MILEPTNAME', 
       'LATITUDENAME', 'LONGITUDNAME', 'HARM_EV', 'MAN_COLL', 'MAN_COLLNAME', 
       'RELJCT1', 'RELJCT1NAME', 'RELJCT2', 'RELJCT2NAME', 'TYP_INT', 
       'REL_ROAD', 'REL_ROADNAME', 'WRK_ZONE', 'WRK_ZONENAME', 'LGT_COND', 
       'WEATHER', 'SCH_BUS', 'SCH_BUSNAME', 'RAIL', 'RAILNAME', 'NOT_HOUR', 'NOT_MIN',
       'ARR_HOUR', 'ARR_MIN', 'HOSP_HR', 'HOSP_MN']

In [6]:
len(columns_to_keep) + len(columns_to_drop)

80

In [7]:
data = accident.drop(columns = columns_to_drop)

In [8]:
vehicle = pd.read_csv(r'C:\DATA ANALYSIS AND DATA SCIENCE PROJECTS\Accident Severity Prediction\data\raw data files\vehicle.csv')
vehicle.head()

C:\Users\Hp\AppData\Local\Temp\ipykernel_17660\2705293479.py:1: DtypeWarning: Columns (53,63,67) have mixed types. Specify dtype option on import or set low_memory=False.
  vehicle = pd.read_csv(r'C:\DATA ANALYSIS AND DATA SCIENCE PROJECTS\Accident Severity Prediction\data\raw data files\vehicle.csv')

,STATE,STATENAME,ST_CASE,VEH_NO,VE_FORMS,MONTH,MONTHNAME,DAY,DAYNAME,HOUR,...,PCRASH4,PCRASH4NAME,PCRASH5,PCRASH5NAME,ACC_TYPE,ACC_TYPENAME,ACC_CONFIG,ACC_CONFIGNAME,MODEL,DEATHS
0,1,Alabama,10001,1,1,1,January,4,4,22,...,3,Skidding laterally clockwise rotation,4,Departed roadway,2,A2-Single Driver-Right Roadside Departure-Cont...,101,Single Driver-Right Roadside Departure,401,1
1,1,Alabama,10002,1,1,3,March,20,20,2,...,1,Tracking,4,Departed roadway,6,B6-Single Driver-Left Roadside Departure-Drive...,102,Single Driver-Left Roadside Departure,25,1
2,1,Alabama,10003,1,1,3,March,18,18,22,...,1,Tracking,4,Departed roadway,6,B6-Single Driver-Left Roadside Departure-Drive...,102,Single Driver-Left Roadside Departure,40,1
3,1,Alabama,10004,1,1,3,March,17,17,19,...,1,Tracking,4,Departed roadway,3,A3-Single Driver-Right Roadside Departure-Avoi...,101,Single Driver-Right Roadside Departure,1,1
4,1,Alabama,10005,1,1,3,March,17,17,14,...,2,Skidding longitudinally rotation less than 30...,4,Departed roadway,2,A2-Single Driver-Right Roadside Departure-Cont...,101,Single Driver-Right Roadside Departure,43,1

In [9]:
print(vehicle.columns)

Index(['STATE', 'STATENAME', 'ST_CASE', 'VEH_NO', 'VE_FORMS', 'MONTH',
       'MONTHNAME', 'DAY', 'DAYNAME', 'HOUR',
       ...
       'PCRASH4', 'PCRASH4NAME', 'PCRASH5', 'PCRASH5NAME', 'ACC_TYPE',
       'ACC_TYPENAME', 'ACC_CONFIG', 'ACC_CONFIGNAME', 'MODEL', 'DEATHS'],
      dtype='object', length=203)

In [10]:
"""1. VPIBODYCLASSNAME: Vehicle type like suv etc
   2. M_HARMNAME: Most harmful event
   3. PREV_SPDNAME: Previous speeding convictions
   4. SPEEDRELNAME: Speeding or not
   5. VALIGNNAME: straight or curve
   6. VPROFILENAME: slope
   7. VSURCONDNAME: Surface condition; dry, wet, snow, etc
   8. """

'1. VPIBODYCLASSNAME: Vehicle type like suv etc\n   2. M_HARMNAME: Most harmful event\n   3. PREV_SPDNAME: Previous speeding convictions\n   4. SPEEDRELNAME: Speeding or not\n   5. VALIGNNAME: straight or curve\n   6. VPROFILENAME: slope\n   7. VSURCONDNAME: Surface condition; dry, wet, snow, etc\n   8. '

In [11]:
columns_to_keep = ['STATENAME', 'ST_CASE', 'VEH_NO', 'NUMOCCSNAME', 'VPICBODYCLASSNAME', 'TRAV_SPNAME', 'DEFORMEDNAME', 
                   'M_HARMNAME', 'DR_DRINKNAME', 'L_STATUSNAME', 'PREV_ACCNAME', 'PREV_SPDNAME', 'SPEEDRELNAME', 
                   'VALIGNNAME', 'VPROFILENAME', 'VSURCONDNAME']
vehicle = vehicle[columns_to_keep]
print(vehicle.head())

  STATENAME  ST_CASE  VEH_NO NUMOCCSNAME  \
0   Alabama    10001       1          01
1   Alabama    10002       1          01
2   Alabama    10003       1          01
3   Alabama    10004       1          03
4   Alabama    10005       1          04

                                   VPICBODYCLASSNAME TRAV_SPNAME  \
0  Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...     055 MPH
1                       Hatchback/Liftback/Notchback     065 MPH
2                                       Sedan/Saloon     060 MPH
3  Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...     060 MPH
4                                       Sedan/Saloon     070 MPH

       DEFORMEDNAME            M_HARMNAME DR_DRINKNAME  L_STATUSNAME  \
0  Disabling Damage            Embankment           No         Valid
1  Disabling Damage  Tree (Standing Only)          Yes         Valid
2  Disabling Damage  Tree (Standing Only)          Yes         Valid
3  Disabling Damage  Tree (Standing Only)          Yes         Valid
4  Disabling Damage  Tree (Standing Only)           No  Not licensed

  PREV_ACCNAME PREV_SPDNAME                  SPEEDRELNAME     VALIGNNAME  \
0          NaN            1                            No       Straight
1          NaN          NaN                            No       Straight
2          NaN          NaN     Yes, Exceeded Speed Limit  Curve - Right
3            1          NaN     Yes, Exceeded Speed Limit   Curve - Left
4          NaN          NaN  Yes, Too Fast for Conditions       Straight

  VPROFILENAME VSURCONDNAME
0     Downhill          Dry
1        Level          Dry
2     Downhill          Dry
3     Downhill          Dry
4        Level          Wet

In [12]:
#data = data.merge(vehicle, on='ST_CASE', how='left')
#data.head()

In [13]:
data.columns

Index(['STATE', 'STATENAME', 'ST_CASE', 'PERNOTMVIT', 'VE_TOTAL', 'VE_FORMS',
       'PVH_INVL', 'PERMVIT', 'CITYNAME', 'MONTHNAME', 'DAYNAME',
       'DAY_WEEKNAME', 'HOUR', 'MINUTE', 'RUR_URBNAME', 'FUNC_SYSNAME',
       'NHSNAME', 'LATITUDE', 'LONGITUD', 'HARM_EVNAME', 'TYP_INTNAME',
       'LGT_CONDNAME', 'WEATHERNAME', 'NOT_HOURNAME', 'NOT_MINNAME',
       'ARR_HOURNAME', 'ARR_MINNAME', 'HOSP_HRNAME', 'HOSP_MNNAME', 'FATALS'],
      dtype='object')

In [14]:
person = pd.read_csv(r'C:\DATA ANALYSIS AND DATA SCIENCE PROJECTS\Accident Severity Prediction\data\raw data files\person.csv')
person.head()

,STATE,STATENAME,ST_CASE,VEH_NO,PER_NO,VE_FORMS,COUNTY,MONTH,MONTHNAME,DAY,...,DEVTYPE,DEVTYPENAME,DEVMOTOR,DEVMOTORNAME,LOCATION,LOCATIONNAME,WORK_INJ,WORK_INJNAME,HISPANIC,HISPANICNAME
0,1,Alabama,10001,1,1,1,13,1,January,4,...,NaN,NaN,NaN,NaN,0,Occupant of a Motor Vehicle,0,No,7,Non-Hispanic
1,1,Alabama,10002,1,1,1,97,3,March,20,...,NaN,NaN,NaN,NaN,0,Occupant of a Motor Vehicle,0,No,7,Non-Hispanic
2,1,Alabama,10003,1,1,1,89,3,March,18,...,NaN,NaN,NaN,NaN,0,Occupant of a Motor Vehicle,0,No,7,Non-Hispanic
3,1,Alabama,10004,1,1,1,53,3,March,17,...,NaN,NaN,NaN,NaN,0,Occupant of a Motor Vehicle,8,Not Applicable (not a fatality),0,Not A Fatality (not Applicable)
4,1,Alabama,10004,1,2,1,53,3,March,17,...,NaN,NaN,NaN,NaN,0,Occupant of a Motor Vehicle,8,Not Applicable (not a fatality),0,Not A Fatality (not Applicable)

In [15]:
columns_to_keep = ['STATE', 'STATENAME', 'ST_CASE', 'VEH_NO', 'AGE', 'INJ_SEVNAME', 'SEXNAME', 'SEAT_POSNAME', 'REST_USENAME', 'DRINKINGNAME', 'ALC_RESNAME', 'LAG_HRSNAME', 'LAG_MINSNAME']
person = person[columns_to_keep]
vehicle_person = vehicle.merge(person, on=['ST_CASE', 'VEH_NO'], how='left')

In [16]:
vehicle_person.head()

,STATENAME_x,ST_CASE,VEH_NO,NUMOCCSNAME,VPICBODYCLASSNAME,TRAV_SPNAME,DEFORMEDNAME,M_HARMNAME,DR_DRINKNAME,L_STATUSNAME,...,STATENAME_y,AGE,INJ_SEVNAME,SEXNAME,SEAT_POSNAME,REST_USENAME,DRINKINGNAME,ALC_RESNAME,LAG_HRSNAME,LAG_MINSNAME
0,Alabama,10001,1,01,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,055 MPH,Disabling Damage,Embankment,No,Valid,...,Alabama,33.0,Fatal Injury (K),Male,"Front Seat, Left Side",Shoulder and Lap Belt Used,No (Alcohol Not Involved),Test Not Given,0,0
1,Alabama,10002,1,01,Hatchback/Liftback/Notchback,065 MPH,Disabling Damage,Tree (Standing Only),Yes,Valid,...,Alabama,32.0,Fatal Injury (K),Female,"Front Seat, Left Side",None Used/Not Applicable,Yes (Alcohol Involved),0.217 % BAC,0,0
2,Alabama,10003,1,01,Sedan/Saloon,060 MPH,Disabling Damage,Tree (Standing Only),Yes,Valid,...,Alabama,21.0,Fatal Injury (K),Female,"Front Seat, Left Side",None Used/Not Applicable,No (Alcohol Not Involved),0.148 % BAC,0,0
3,Alabama,10004,1,03,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,060 MPH,Disabling Damage,Tree (Standing Only),Yes,Valid,...,Alabama,54.0,Suspected Serious Injury (A),Male,"Front Seat, Left Side",Shoulder and Lap Belt Used,Yes (Alcohol Involved),0.117 % BAC,Unknown,Unknown
4,Alabama,10004,1,03,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,060 MPH,Disabling Damage,Tree (Standing Only),Yes,Valid,...,Alabama,53.0,Suspected Serious Injury (A),Male,"Front Seat, Right Side",Shoulder and Lap Belt Used,Not Reported,Test Not Given,Unknown,Unknown

In [17]:
len(vehicle_person.columns)

27

In [18]:
vehicle_person.columns

Index(['STATENAME_x', 'ST_CASE', 'VEH_NO', 'NUMOCCSNAME', 'VPICBODYCLASSNAME',
       'TRAV_SPNAME', 'DEFORMEDNAME', 'M_HARMNAME', 'DR_DRINKNAME',
       'L_STATUSNAME', 'PREV_ACCNAME', 'PREV_SPDNAME', 'SPEEDRELNAME',
       'VALIGNNAME', 'VPROFILENAME', 'VSURCONDNAME', 'STATE', 'STATENAME_y',
       'AGE', 'INJ_SEVNAME', 'SEXNAME', 'SEAT_POSNAME', 'REST_USENAME',
       'DRINKINGNAME', 'ALC_RESNAME', 'LAG_HRSNAME', 'LAG_MINSNAME'],
      dtype='object')

In [19]:
vehicle_person = vehicle_person.drop(columns=['STATENAME_x'])
vehicle_person = vehicle_person.rename(columns={'STATENAME_y': 'STATENAME'})
cols = list(vehicle_person.columns)
cols.remove('STATENAME')
cols.insert(1, 'STATENAME')
vehicle_person = vehicle_person[cols]

In [20]:
vehicle_person.columns

Index(['ST_CASE', 'STATENAME', 'VEH_NO', 'NUMOCCSNAME', 'VPICBODYCLASSNAME',
       'TRAV_SPNAME', 'DEFORMEDNAME', 'M_HARMNAME', 'DR_DRINKNAME',
       'L_STATUSNAME', 'PREV_ACCNAME', 'PREV_SPDNAME', 'SPEEDRELNAME',
       'VALIGNNAME', 'VPROFILENAME', 'VSURCONDNAME', 'STATE', 'AGE',
       'INJ_SEVNAME', 'SEXNAME', 'SEAT_POSNAME', 'REST_USENAME',
       'DRINKINGNAME', 'ALC_RESNAME', 'LAG_HRSNAME', 'LAG_MINSNAME'],
      dtype='object')

In [21]:
vehicle_person.to_csv('combined_vehicle_person.csv', index=False)

In [22]:
vehicle_person = vehicle_person.drop(columns=['STATE'])

In [23]:
vehicle_person = vehicle_person.rename(columns={
    'ST_CASE': 'Crash_ID',
    'VEH_NO': 'Vehicle_ID',
    'NUMOCCSNAME': 'Num_Occupants',
    'STATENAME': 'State_Name',
    'VPICBODYCLASSNAME': 'Vehicle_Body_Type',
    'TRAV_SPNAME': 'Travel_Speed_Limit', 
    'DEFORMEDNAME': 'Vehicle_Damage_Extent',
    'M_HARMNAME': 'First_Harmful_Event',
    'DR_DRINKNAME': 'Driver_Drinking_Status',
    'L_STATUSNAME': 'License_Status',
    'PREV_ACCNAME': 'Previous_Accident_Flag',
    'PREV_SPDNAME': 'Previous_Speeding_Flag',
    'SPEEDRELNAME': 'Speed_Related_Flag',
    'ALC_RESNAME': 'Alcohol_Test_Result', 
    'VALIGNNAME': 'Road_Horizontal_Alignment',  # Straight or Curve
    'VPROFILENAME': 'Road_Vertical_Profile',    # Level or Slope
    'VSURCONDNAME': 'Road_Surface_Condition',   # Dry, Wet, Snow
    'AGE': 'Age',
    'SEXNAME': 'Sex',
    'SEAT_POSNAME': 'Seat_Position',
    'REST_USENAME': 'Restraint_Use',
    'DRINKINGNAME': 'Drinking_Report',         
    'INJ_SEVNAME': 'Injury_Severity',   
    'LAG_HRSNAME': 'Time_to_Death_Hours',
    'LAG_MINSNAME': 'Time_to_Death_Minutes'
})

In [24]:
new_order = [
    'Crash_ID', 'Vehicle_ID', 'State_Name',
    'Injury_Severity', 'Time_to_Death_Hours', 'Time_to_Death_Minutes',
    'Age', 'Sex', 'Seat_Position', 'Num_Occupants', 'Restraint_Use',
    'Drinking_Report', 'Alcohol_Test_Result', 'Driver_Drinking_Status',
    'License_Status', 'Previous_Accident_Flag', 'Previous_Speeding_Flag', 'Speed_Related_Flag',
    'Vehicle_Body_Type', 'Vehicle_Damage_Extent', 'First_Harmful_Event', 'Travel_Speed_Limit',
    'Road_Surface_Condition', 'Road_Horizontal_Alignment', 'Road_Vertical_Profile']

vehicle_person = vehicle_person[new_order]

In [25]:
vehicle_person.head()

,Crash_ID,Vehicle_ID,State_Name,Injury_Severity,Time_to_Death_Hours,Time_to_Death_Minutes,Age,Sex,Seat_Position,Num_Occupants,...,Previous_Accident_Flag,Previous_Speeding_Flag,Speed_Related_Flag,Vehicle_Body_Type,Vehicle_Damage_Extent,First_Harmful_Event,Travel_Speed_Limit,Road_Surface_Condition,Road_Horizontal_Alignment,Road_Vertical_Profile
0,10001,1,Alabama,Fatal Injury (K),0,0,33.0,Male,"Front Seat, Left Side",01,...,NaN,1,No,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Disabling Damage,Embankment,055 MPH,Dry,Straight,Downhill
1,10002,1,Alabama,Fatal Injury (K),0,0,32.0,Female,"Front Seat, Left Side",01,...,NaN,NaN,No,Hatchback/Liftback/Notchback,Disabling Damage,Tree (Standing Only),065 MPH,Dry,Straight,Level
2,10003,1,Alabama,Fatal Injury (K),0,0,21.0,Female,"Front Seat, Left Side",01,...,NaN,NaN,"Yes, Exceeded Speed Limit",Sedan/Saloon,Disabling Damage,Tree (Standing Only),060 MPH,Dry,Curve - Right,Downhill
3,10004,1,Alabama,Suspected Serious Injury (A),Unknown,Unknown,54.0,Male,"Front Seat, Left Side",03,...,1,NaN,"Yes, Exceeded Speed Limit",Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Disabling Damage,Tree (Standing Only),060 MPH,Dry,Curve - Left,Downhill
4,10004,1,Alabama,Suspected Serious Injury (A),Unknown,Unknown,53.0,Male,"Front Seat, Right Side",03,...,1,NaN,"Yes, Exceeded Speed Limit",Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Disabling Damage,Tree (Standing Only),060 MPH,Dry,Curve - Left,Downhill

In [26]:
vehicle_person['Injury_Severity'].unique()

array(['Fatal Injury (K)', 'Suspected Serious Injury (A)',
       'Suspected Minor Injury (B)', 'No Apparent Injury (O)',
       'Possible Injury (C)', nan, 'Unknown/Not Reported',
       'Injured, Severity Unknown', 'Died Prior to Crash'], dtype=object)

In [27]:
vehicle_person['Is_Killed'] = vehicle_person['Injury_Severity'].apply(
    lambda x: 1 if x in ['Fatal Injury (K)', 'Died Prior to Crash'] else 0
)

non_fatal_categories = [
    'Suspected Serious Injury (A)',
    'Suspected Minor Injury (B)',
    'No Apparent Injury (O)',
    'Possible Injury (C)'
]

vehicle_person['Is_Alive'] = vehicle_person['Injury_Severity'].apply(
    lambda x: 1 if x in non_fatal_categories else 0
)

total_killed_alive = vehicle_person.groupby('Crash_ID').agg(
    Total_Killed=('Is_Killed', 'sum'),
    Total_Alive=('Is_Alive', 'sum')
).reset_index()

In [28]:
total_killed_alive.head()

   Crash_ID  Total_Killed  Total_Alive
0     10001             1            0
1     10002             1            0
2     10003             1            0
3     10004             1            2
4     10005             1            3

In [29]:
vehicle_person.head()

,Crash_ID,Vehicle_ID,State_Name,Injury_Severity,Time_to_Death_Hours,Time_to_Death_Minutes,Age,Sex,Seat_Position,Num_Occupants,...,Speed_Related_Flag,Vehicle_Body_Type,Vehicle_Damage_Extent,First_Harmful_Event,Travel_Speed_Limit,Road_Surface_Condition,Road_Horizontal_Alignment,Road_Vertical_Profile,Is_Killed,Is_Alive
0,10001,1,Alabama,Fatal Injury (K),0,0,33.0,Male,"Front Seat, Left Side",01,...,No,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Disabling Damage,Embankment,055 MPH,Dry,Straight,Downhill,1,0
1,10002,1,Alabama,Fatal Injury (K),0,0,32.0,Female,"Front Seat, Left Side",01,...,No,Hatchback/Liftback/Notchback,Disabling Damage,Tree (Standing Only),065 MPH,Dry,Straight,Level,1,0
2,10003,1,Alabama,Fatal Injury (K),0,0,21.0,Female,"Front Seat, Left Side",01,...,"Yes, Exceeded Speed Limit",Sedan/Saloon,Disabling Damage,Tree (Standing Only),060 MPH,Dry,Curve - Right,Downhill,1,0
3,10004,1,Alabama,Suspected Serious Injury (A),Unknown,Unknown,54.0,Male,"Front Seat, Left Side",03,...,"Yes, Exceeded Speed Limit",Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Disabling Damage,Tree (Standing Only),060 MPH,Dry,Curve - Left,Downhill,0,1
4,10004,1,Alabama,Suspected Serious Injury (A),Unknown,Unknown,53.0,Male,"Front Seat, Right Side",03,...,"Yes, Exceeded Speed Limit",Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Disabling Damage,Tree (Standing Only),060 MPH,Dry,Curve - Left,Downhill,0,1

In [30]:
vehicle_person.columns

Index(['Crash_ID', 'Vehicle_ID', 'State_Name', 'Injury_Severity',
       'Time_to_Death_Hours', 'Time_to_Death_Minutes', 'Age', 'Sex',
       'Seat_Position', 'Num_Occupants', 'Restraint_Use', 'Drinking_Report',
       'Alcohol_Test_Result', 'Driver_Drinking_Status', 'License_Status',
       'Previous_Accident_Flag', 'Previous_Speeding_Flag',
       'Speed_Related_Flag', 'Vehicle_Body_Type', 'Vehicle_Damage_Extent',
       'First_Harmful_Event', 'Travel_Speed_Limit', 'Road_Surface_Condition',
       'Road_Horizontal_Alignment', 'Road_Vertical_Profile', 'Is_Killed',
       'Is_Alive'],
      dtype='object')

In [31]:
vehicle_person['Sex'].unique()

array(['Male', 'Female', nan, 'Reported as Unknown', 'Not Reported'],
      dtype=object)

In [32]:
vehicle_person['Num_Occupants'].unique()

array(['01', '03', '04', '02', nan, 'Unknown', '06', '09', '05', '12',
       '40', '07', '08', '11', '10', '13', '14', '19', '21', '15', '39',
       '38', '33', '44', '27', '43', '18', '49', '28', '17', '23', '16'],
      dtype=object)

In [33]:
#If pandas encounters any non-numeric text, blank cells, or any value it cannot safely convert to a number, 
# it will "coerce" that value by replacing it with NaN

#Age
vehicle_person['Age'] = pd.to_numeric(vehicle_person['Age'], errors='coerce')
median_age = vehicle_person['Age'].median()
vehicle_person['Age'] = vehicle_person['Age'].fillna(median_age).astype(int)

#Sex
sex_mapping = {
    'Male': 'Male',
    'Female': 'Female',
    'Reported as Unknown': 'Other',
    'Not Reported': 'Other'
}
vehicle_person['Sex'] = vehicle_person['Sex'].map(sex_mapping).fillna('Other')

#Hours and Minutes and Occupants
def convert_time_to_int(col_val):
    col_val = pd.to_numeric(col_val, errors='coerce').fillna(0)
    return col_val.astype(int)

vehicle_person['Time_to_Death_Hours'] = convert_time_to_int(vehicle_person['Time_to_Death_Hours'])
vehicle_person['Time_to_Death_Minutes'] = convert_time_to_int(vehicle_person['Time_to_Death_Minutes'])
vehicle_person['Num_Occupants'] = convert_time_to_int(vehicle_person['Num_Occupants'])
#to_numeric(): chances for error handling(coerce, raise, ignore)
#astype(): strict enforcer

In [34]:
vehicle_person.head()

,Crash_ID,Vehicle_ID,State_Name,Injury_Severity,Time_to_Death_Hours,Time_to_Death_Minutes,Age,Sex,Seat_Position,Num_Occupants,...,Speed_Related_Flag,Vehicle_Body_Type,Vehicle_Damage_Extent,First_Harmful_Event,Travel_Speed_Limit,Road_Surface_Condition,Road_Horizontal_Alignment,Road_Vertical_Profile,Is_Killed,Is_Alive
0,10001,1,Alabama,Fatal Injury (K),0,0,33,Male,"Front Seat, Left Side",1,...,No,Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Disabling Damage,Embankment,055 MPH,Dry,Straight,Downhill,1,0
1,10002,1,Alabama,Fatal Injury (K),0,0,32,Female,"Front Seat, Left Side",1,...,No,Hatchback/Liftback/Notchback,Disabling Damage,Tree (Standing Only),065 MPH,Dry,Straight,Level,1,0
2,10003,1,Alabama,Fatal Injury (K),0,0,21,Female,"Front Seat, Left Side",1,...,"Yes, Exceeded Speed Limit",Sedan/Saloon,Disabling Damage,Tree (Standing Only),060 MPH,Dry,Curve - Right,Downhill,1,0
3,10004,1,Alabama,Suspected Serious Injury (A),0,0,54,Male,"Front Seat, Left Side",3,...,"Yes, Exceeded Speed Limit",Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Disabling Damage,Tree (Standing Only),060 MPH,Dry,Curve - Left,Downhill,0,1
4,10004,1,Alabama,Suspected Serious Injury (A),0,0,53,Male,"Front Seat, Right Side",3,...,"Yes, Exceeded Speed Limit",Sport Utility Vehicle (SUV)/Multi-Purpose Vehi...,Disabling Damage,Tree (Standing Only),060 MPH,Dry,Curve - Left,Downhill,0,1

In [35]:
vehicle_person['Seat_Position'].unique()

array(['Front Seat, Left Side', 'Front Seat, Right Side',
       'Second Seat, Right Side', 'Second Seat, Left Side',
       'Third Seat, Right Side',
       'Other Passenger in enclosed passenger or cargo area', nan,
       'Third Seat, Left Side', 'Second Seat, Middle', 'Trailing Unit',
       'Front Seat, Middle',
       'Other Passenger in unenclosed passenger or cargo area',
       'Not Reported', 'Second Seat, Unknown', 'Reported as Unknown',
       'Riding on Exterior of Vehicle', 'Front Seat, Unknown',
       'Third Seat, Other', 'Sleeper Section of Cab (Truck)',
       'Second Seat, Other', 'Third Seat, Middle',
       'Other Passenger in passenger or cargo area, unknown whether or not enclosed',
       'Fourth Seat, Unknown', 'Third Seat, Unknown',
       'Appended to a Motor Vehicle for Motion', 'Fourth Seat, Middle',
       'Front Seat, Other', 'Fourth Seat, Left Side',
       'Fourth Seat, Right Side'], dtype=object)

In [36]:
#Seats
def categorize_seat_revised(position):
    if pd.isna(position):
        return 'Front_Passenger'
    
    position_std = str(position).strip().upper()
    
    high_risk_keywords = [
        'EXTERIOR', 'TRAILING UNIT', 'SLEEPER SECTION', 'APPENDED',
        'ENCLOSED PASSENGER OR CARGO AREA',  
    ]
    if any(keyword in position_std for keyword in high_risk_keywords):
        return 'Non_Standard_Risk'
   
    if position_std == 'FRONT SEAT, LEFT SIDE':
        return 'Driver'
    
    elif 'FRONT SEAT' in position_std:
        return 'Front_Passenger'
    
    elif 'SECOND SEAT' in position_std or 'THIRD SEAT' in position_std or 'FOURTH SEAT' in position_std:
        return 'Rear_Seat'

    return 'Front_Passenger'

vehicle_person['Seat_Category'] = vehicle_person['Seat_Position'].apply(categorize_seat_revised)
vehicle_person = vehicle_person.drop(columns=['Seat_Position'])

vehicle_person['Killed_Seat_Position'] = vehicle_person.apply(
    lambda row: row['Seat_Category'] if row['Is_Killed'] == 1 else 'Not Applicable',
    axis=1
)

def get_fatal_seats_list(series):
    fatal_seats = series[series != 'Not Applicable']
    return fatal_seats.tolist()

total_killed_alive = vehicle_person.groupby('Crash_ID').agg(
    Total_Killed=('Is_Killed', 'sum'),
    Total_Alive=('Is_Alive', 'sum'),
    Fatal_Seats_List=('Killed_Seat_Position', get_fatal_seats_list)
).reset_index()

print(total_killed_alive.head())

   Crash_ID  Total_Killed  Total_Alive Fatal_Seats_List
0     10001             1            0         [Driver]
1     10002             1            0         [Driver]
2     10003             1            0         [Driver]
3     10004             1            2      [Rear_Seat]
4     10005             1            3         [Driver]

In [37]:
vehicle_person.columns

Index(['Crash_ID', 'Vehicle_ID', 'State_Name', 'Injury_Severity',
       'Time_to_Death_Hours', 'Time_to_Death_Minutes', 'Age', 'Sex',
       'Num_Occupants', 'Restraint_Use', 'Drinking_Report',
       'Alcohol_Test_Result', 'Driver_Drinking_Status', 'License_Status',
       'Previous_Accident_Flag', 'Previous_Speeding_Flag',
       'Speed_Related_Flag', 'Vehicle_Body_Type', 'Vehicle_Damage_Extent',
       'First_Harmful_Event', 'Travel_Speed_Limit', 'Road_Surface_Condition',
       'Road_Horizontal_Alignment', 'Road_Vertical_Profile', 'Is_Killed',
       'Is_Alive', 'Seat_Category', 'Killed_Seat_Position'],
      dtype='object')

In [38]:
vehicle_person['Restraint_Use'].unique()

array(['Shoulder and Lap Belt Used', 'None Used/Not Applicable',
       'Reported as Unknown', 'Lap Belt Only Used', nan,
       'Child Restraint System - Forward Facing', 'Booster Seat',
       'Child Restraint System - Rear Facing', 'Not Reported', 'Other',
       'Child Restraint Type Unknown', 'Shoulder Belt Only Used',
       'Restraint Used - Type Unknown', 'Racing-Style Harness Used'],
      dtype=object)

In [39]:
#Restraint_Use

def categorize_restraint(restraint):
    if pd.isna(restraint):
        return 'Shoulder_Lapbelt'
    
    restraint_std = str(restraint).strip().upper()

    if 'SHOULDER AND LAP BELT USED' in restraint_std:
        return 'Shoulder_Lapbelt'
    elif 'CHILD' in restraint_std or 'BOOSTER SEAT' in restraint_std:
        return 'Child_Safety'
    elif 'SHOULDER BELT ONLY USED' in restraint_std:
        return 'Shoulder_Only'
    elif 'LAP BELT ONLY USED' in restraint_std:
        return 'Lapbelt_Only'
    elif 'NONE USED' in restraint_std:
        return 'None_Used'
    return 'Shoulder_Lapbelt'

vehicle_person['Restraint_Category'] = vehicle_person['Restraint_Use'].apply(categorize_restraint)
vehicle_person = vehicle_person.drop(columns=['Restraint_Use'])

vehicle_person['Killed_Restraint_Status'] = vehicle_person.apply(
    lambda row: row['Restraint_Category'] if row['Is_Killed'] == 1 else 'Not Applicable',
    axis=1
)

restraint_features = vehicle_person.groupby('Crash_ID').agg(
    Killed_Restraint_List=('Killed_Restraint_Status', get_fatal_seats_list)
).reset_index()

total_killed_alive = total_killed_alive.merge(
    restraint_features,
    on='Crash_ID',
    how='left' 
)

In [40]:
restraint_mode = vehicle_person['Restraint_Category'].mode().iloc[0]
print(restraint_mode)

Shoulder_Lapbelt

In [41]:
print(total_killed_alive.head(10))

   Crash_ID  Total_Killed  Total_Alive              Fatal_Seats_List  \
0     10001             1            0                      [Driver]
1     10002             1            0                      [Driver]
2     10003             1            0                      [Driver]
3     10004             1            2                   [Rear_Seat]
4     10005             1            3                      [Driver]
5     10006             1            0                      [Driver]
6     10007             2            0              [Driver, Driver]
7     10008             1            1             [Front_Passenger]
8     10009             2            1  [Front_Passenger, Rear_Seat]
9     10010             1            3                      [Driver]

    Killed_Restraint_List
0      [Shoulder_Lapbelt]
1             [None_Used]
2             [None_Used]
3             [None_Used]
4      [Shoulder_Lapbelt]
5      [Shoulder_Lapbelt]
6  [None_Used, None_Used]
7             [None_Used]
8  [None_Used, None_Used]
9      [Shoulder_Lapbelt]

In [42]:
print(vehicle_person['Drinking_Report'].unique())
print(vehicle_person['Alcohol_Test_Result'].unique())
print(vehicle_person['Driver_Drinking_Status'].unique())

['No (Alcohol Not Involved)' 'Yes (Alcohol Involved)' 'Not Reported'
 'Reported as Unknown' nan]
['Test Not Given' '0.217 % BAC' '0.148 % BAC' '0.117 % BAC' '0.178 % BAC'
 '0.000 % BAC' '0.053 % BAC' '0.057 % BAC' '0.183 % BAC' '0.086 % BAC'
 '0.150 % BAC' nan '0.137 % BAC' '0.393 % BAC' '0.190 % BAC' '0.142 % BAC'
 '0.025 % BAC' '0.111 % BAC' '0.180 % BAC' '0.204 % BAC' '0.373 % BAC'
 '0.292 % BAC' '0.249 % BAC' '0.232 % BAC' '0.102 % BAC' '0.120 % BAC'
 '0.166 % BAC' '0.073 % BAC' '0.054 % BAC' '0.196 % BAC' '0.055 % BAC'
 '0.234 % BAC' '0.237 % BAC' '0.268 % BAC' '0.362 % BAC' '0.129 % BAC'
 '0.149 % BAC' '0.438 % BAC' '0.245 % BAC' '0.347 % BAC' '0.193 % BAC'
 '0.123 % BAC' '0.171 % BAC' '0.151 % BAC' '0.126 % BAC' '0.036 % BAC'
 '0.144 % BAC' '0.029 % BAC' '0.108 % BAC' '0.147 % BAC' '0.140 % BAC'
 '0.023 % BAC' '0.279 % BAC' '0.158 % BAC' '0.227 % BAC' '0.215 % BAC'
 '0.301 % BAC' '0.243 % BAC' '0.020 % BAC' '0.219 % BAC' '0.233 % BAC'
 '0.070 % BAC' '0.010 % BAC' '0.274 % BAC' '0.154 % BAC' '0.289 % BAC'
 '0.039 % BAC' '0.164 % BAC' '0.224 % BAC' '0.189 % BAC' '0.145 % BAC'
 '0.032 % BAC' '0.199 % BAC' '0.351 % BAC' '0.134 % BAC' '0.157 % BAC'
 '0.138 % BAC' '0.083 % BAC' '0.201 % BAC' '0.077 % BAC' '0.212 % BAC'
 '0.167 % BAC' '0.128 % BAC' '0.221 % BAC' '0.131 % BAC' '0.184 % BAC'
 '0.106 % BAC' '0.021 % BAC' '0.294 % BAC' '0.104 % BAC' '0.068 % BAC'
 '0.230 % BAC' '0.205 % BAC' '0.342 % BAC' '0.210 % BAC' '0.203 % BAC'
 '0.307 % BAC' '0.026 % BAC' '0.081 % BAC' '0.072 % BAC' '0.135 % BAC'
 '0.291 % BAC' '0.024 % BAC' '0.110 % BAC' '0.046 % BAC' '0.100 % BAC'
 '0.133 % BAC' '0.156 % BAC' '0.065 % BAC' '0.038 % BAC' '0.121 % BAC'
 '0.353 % BAC' '0.103 % BAC' '0.162 % BAC' '0.392 % BAC'
 'Reported as Unknown if Tested' '0.163 % BAC' '0.197 % BAC' '0.226 % BAC'
 '0.251 % BAC' '0.084 % BAC' '0.045 % BAC' '0.047 % BAC' '0.082 % BAC'
 '0.125 % BAC' '0.112 % BAC' '0.320 % BAC' '0.074 % BAC' '0.041 % BAC'
 '0.078 % BAC' '0.059 % BAC' '0.098 % BAC' '0.270 % BAC' '0.209 % BAC'
 '0.061 % BAC' '0.013 % BAC' '0.022 % BAC' '0.225 % BAC' '0.155 % BAC'
 '0.257 % BAC' '0.338 % BAC' '0.277 % BAC' '0.325 % BAC' '0.119 % BAC'
 '0.252 % BAC' '0.283 % BAC' '0.214 % BAC' '0.027 % BAC' '0.186 % BAC'
 '0.130 % BAC' '0.066 % BAC' '0.182 % BAC' '0.113 % BAC' '0.272 % BAC'
 '0.114 % BAC' '0.097 % BAC' '0.124 % BAC' '0.105 % BAC' '0.699 % BAC'
 '0.218 % BAC' '0.030 % BAC' '0.265 % BAC' '0.044 % BAC' '0.281 % BAC'
 '0.255 % BAC' '0.043 % BAC' '0.259 % BAC' '0.229 % BAC' '0.139 % BAC'
 'Not Reported' '0.258 % BAC' '0.064 % BAC' '0.207 % BAC' '0.160 % BAC'
 '0.169 % BAC' '0.297 % BAC' '0.200 % BAC' '0.247 % BAC'
 'AC Test Performed, Results Unknown' '0.446 % BAC' '0.359 % BAC'
 '0.368 % BAC' '0.076 % BAC' '0.300 % BAC'
 'Positive Reading with No Actual Value' '0.208 % BAC' '0.019 % BAC'
 '0.058 % BAC' '0.168 % BAC' '0.101 % BAC' '0.213 % BAC' '0.191 % BAC'
 '0.231 % BAC' '0.177 % BAC' '0.107 % BAC' '0.220 % BAC' '0.264 % BAC'
 '0.244 % BAC' '0.246 % BAC' '0.170 % BAC' '0.282 % BAC' '0.239 % BAC'
 '0.050 % BAC' '0.179 % BAC' '0.308 % BAC' '0.014 % BAC' '0.088 % BAC'
 '0.071 % BAC' '0.256 % BAC' '0.116 % BAC' '0.271 % BAC' '0.096 % BAC'
 '0.091 % BAC' '0.267 % BAC' '0.317 % BAC' '0.173 % BAC' '0.181 % BAC'
 '0.153 % BAC' '0.188 % BAC' '0.099 % BAC' '0.906 % BAC' '0.015 % BAC'
 '0.012 % BAC' '0.037 % BAC' '0.236 % BAC' '0.062 % BAC' '0.080 % BAC'
 '0.033 % BAC' '0.195 % BAC' '0.303 % BAC' '0.165 % BAC' '0.211 % BAC'
 '0.228 % BAC' '0.269 % BAC' '0.263 % BAC' '0.136 % BAC' '0.042 % BAC'
 '0.298 % BAC' '0.290 % BAC' '0.194 % BAC' '0.090 % BAC' '0.018 % BAC'
 '0.250 % BAC' '0.011 % BAC' '0.202 % BAC' '0.276 % BAC' '0.242 % BAC'
 '0.152 % BAC' '0.223 % BAC' '0.094 % BAC' '0.127 % BAC' '0.146 % BAC'
 '0.075 % BAC' '0.159 % BAC' '0.331 % BAC' '0.016 % BAC' '0.031 % BAC'
 '0.235 % BAC' '0.352 % BAC' '0.085 % BAC' '0.248 % BAC' '0.176 % BAC'
 '0.240 % BAC' '0.273 % BAC' '0.185 % BAC' '0.330 % BAC' '0.410 % BAC'
 '0.400 % BAC' '0.360 % BAC' '0.530 % BAC' '0.051 % BAC' '0.293 % BAC'
 '0.480 % BAC' '0.260 % BAC' '0.378 % BAC' '0.161 % BAC' '0.122 % BAC'
 '0.192 % BAC' '0.280 % BAC' '0.040 % BAC' '0.310 % BAC' '0.254 % BAC'
 '0.680 % BAC' '0.500 % BAC' '0.118 % BAC' '0.063 % BAC' '0.380 % BAC'
 '0.132 % BAC' '0.187 % BAC' '0.017 % BAC' '0.052 % BAC' '0.261 % BAC'
 '0.350 % BAC' '0.056 % BAC' '0.174 % BAC' '0.006 % BAC' '0.284 % BAC'
 '0.109 % BAC' '0.390 % BAC' '0.060 % BAC' '0.357 % BAC' '0.334 % BAC'
 '0.048 % BAC' '0.216 % BAC' '0.324 % BAC' '0.340 % BAC' '0.321 % BAC'
 '0.143 % BAC' '0.069 % BAC' '0.115 % BAC' '0.005 % BAC' '0.095 % BAC'
 '0.309 % BAC' '0.067 % BAC' '0.388 % BAC' '0.172 % BAC' '0.405 % BAC'
 '0.089 % BAC' '0.093 % BAC' '0.356 % BAC' '0.035 % BAC' '0.222 % BAC'
 '0.329 % BAC' '0.348 % BAC' '0.286 % BAC' '0.238 % BAC' '0.326 % BAC'
 '0.141 % BAC' '0.275 % BAC' '0.313 % BAC' '0.175 % BAC' '0.241 % BAC'
 '0.034 % BAC' '0.285 % BAC' '0.028 % BAC' '0.296 % BAC' '0.371 % BAC'
 '0.198 % BAC' '0.364 % BAC' '0.299 % BAC' '0.253 % BAC' '0.295 % BAC'
 '0.397 % BAC' '0.327 % BAC' '0.312 % BAC' '0.345 % BAC' '0.354 % BAC'
 '0.206 % BAC' '0.262 % BAC' '0.092 % BAC' '0.365 % BAC' '0.049 % BAC'
 '0.302 % BAC' '0.087 % BAC' '0.370 % BAC' '0.440 % BAC' '0.266 % BAC'
 '0.315 % BAC' '0.406 % BAC' '0.008 % BAC' '0.420 % BAC' '0.079 % BAC'
 '0.328 % BAC' '0.343 % BAC' '0.316 % BAC' '0.318 % BAC' '0.002 % BAC'
 '0.396 % BAC' '0.339 % BAC' '0.306 % BAC' '0.335 % BAC' '0.305 % BAC'
 '0.383 % BAC' '0.361 % BAC' '0.319 % BAC' '0.332 % BAC' '0.463 % BAC'
 '0.860 % BAC' '0.377 % BAC' '0.650 % BAC' '0.314 % BAC' '0.337 % BAC'
 '0.590 % BAC' '0.007 % BAC' '0.001 % BAC' '.94 % or Greater'
 '0.287 % BAC' '0.449 % BAC' '0.561 % BAC' '0.341 % BAC' '0.304 % BAC'
 '0.323 % BAC' '0.344 % BAC' '0.333 % BAC' '0.336 % BAC' '0.288 % BAC'
 '0.311 % BAC' '0.437 % BAC' '0.322 % BAC' '0.004 % BAC' '0.384 % BAC'
 '0.790 % BAC' '0.278 % BAC' '0.389 % BAC' '0.479 % BAC' '0.349 % BAC'
 '0.346 % BAC' '0.414 % BAC' '0.424 % BAC' '0.436 % BAC' '0.423 % BAC'
 '0.355 % BAC' '0.363 % BAC' '0.519 % BAC' '0.476 % BAC' '0.495 % BAC'
 '0.430 % BAC' '0.570 % BAC' '0.533 % BAC' '0.470 % BAC' '0.386 % BAC'
 '0.399 % BAC' '0.367 % BAC' '0.381 % BAC' '0.451 % BAC' '0.366 % BAC'
 '0.413 % BAC' '0.395 % BAC' '0.450 % BAC' '0.431 % BAC' '0.511 % BAC'
 '0.425 % BAC' '0.432 % BAC' '0.478 % BAC' '0.358 % BAC' '0.387 % BAC'
 '0.465 % BAC' '0.404 % BAC' '0.615 % BAC' '0.471 % BAC' '0.418 % BAC'
 '0.489 % BAC' '0.600 % BAC' '0.374 % BAC' '0.385 % BAC' '0.686 % BAC'
 '0.376 % BAC' '0.630 % BAC' '0.382 % BAC']
['No' 'Yes']

In [43]:
#Alcohol

def any_driver_drinking_flag(row):
    if row['Seat_Category'] == 'Driver':
        driver_status_std = str(row['Driver_Drinking_Status']).strip().upper()
        if driver_status_std == 'YES':
            return 1
        return 0
    return 0

vehicle_person['Is_Drinking_Driver_Flag'] = vehicle_person.apply(
    any_driver_drinking_flag, 
    axis=1
)

driver_drinking_flag_features = vehicle_person.groupby('Crash_ID').agg(
    Any_Driver_Drinking=('Is_Drinking_Driver_Flag', 'max')
).reset_index()

total_killed_alive = total_killed_alive.merge(
    driver_drinking_flag_features,
    on='Crash_ID',
    how='left'
)

vehicle_person = vehicle_person.drop(columns=[
    'Drinking_Report', 'Alcohol_Test_Result', 'Driver_Drinking_Status'
])

In [44]:
driver_drinking_count = vehicle_person.groupby('Crash_ID').agg(
    Total_Drinking_Drivers=('Is_Drinking_Driver_Flag', 'sum')
).reset_index()

total_killed_alive = total_killed_alive.merge(
    driver_drinking_count,
    on='Crash_ID',
    how='left'
)

In [45]:
total_killed_alive.head(10)

,Crash_ID,Total_Killed,Total_Alive,Fatal_Seats_List,Killed_Restraint_List,Any_Driver_Drinking,Total_Drinking_Drivers
0,10001,1,0,[Driver],[Shoulder_Lapbelt],0,0
1,10002,1,0,[Driver],[None_Used],1,1
2,10003,1,0,[Driver],[None_Used],1,1
3,10004,1,2,[Rear_Seat],[None_Used],1,1
4,10005,1,3,[Driver],[Shoulder_Lapbelt],0,0
5,10006,1,0,[Driver],[Shoulder_Lapbelt],0,0
6,10007,2,0,"[Driver, Driver]","[None_Used, None_Used]",0,0
7,10008,1,1,[Front_Passenger],[None_Used],0,0
8,10009,2,1,"[Front_Passenger, Rear_Seat]","[None_Used, None_Used]",1,1
9,10010,1,3,[Driver],[Shoulder_Lapbelt],1,2

In [46]:
vehicle_person.columns

Index(['Crash_ID', 'Vehicle_ID', 'State_Name', 'Injury_Severity',
       'Time_to_Death_Hours', 'Time_to_Death_Minutes', 'Age', 'Sex',
       'Num_Occupants', 'License_Status', 'Previous_Accident_Flag',
       'Previous_Speeding_Flag', 'Speed_Related_Flag', 'Vehicle_Body_Type',
       'Vehicle_Damage_Extent', 'First_Harmful_Event', 'Travel_Speed_Limit',
       'Road_Surface_Condition', 'Road_Horizontal_Alignment',
       'Road_Vertical_Profile', 'Is_Killed', 'Is_Alive', 'Seat_Category',
       'Killed_Seat_Position', 'Restraint_Category', 'Killed_Restraint_Status',
       'Is_Drinking_Driver_Flag'],
      dtype='object')

In [47]:
print(vehicle_person['License_Status'].unique())
print(vehicle_person['Previous_Accident_Flag'].unique())
print(vehicle_person['Previous_Speeding_Flag'].unique())

['Valid' 'Not licensed' 'Suspended'
 'No Driver Present/Unknown if Driver Present' 'Expired' 'Revoked'
 'Unknown License Status' 'Canceled or denied']
[nan '1' '4' '2' 'No Driver Present/Unknown if Driver Present'
 'Crashes Not Reported on Driving Record' 'Unknown' '5' '3' '6' '7' '8']
['1' nan 'No Driver Present/Unknown if Driver Present' '5' '2' 'Unknown'
 '3' '4' '7' '6' '8' '13' '9' '14']

In [48]:
import numpy as np
def categorize_license(status):
    if pd.isna(status):
        return 'Invalid'
    
    status_std = str(status).strip().upper()

    if status_std == 'VALID':
        return 'Valid'
    elif status_std in ['NOT LICENSED', 'SUSPENDED', 'EXPIRED', 'REVOKED', 'CANCELED OR DENIED']:
        return 'Invalid'
    else:
        return 'Invalid'

vehicle_person['License_Category'] = vehicle_person['License_Status'].apply(categorize_license)
vehicle_person = vehicle_person.drop(columns=['License_Status'])

vehicle_person['Driver_License_Category'] = np.where(
    vehicle_person['Seat_Category'] == 'Driver', 
    vehicle_person['License_Category'], 
    np.nan
)

history_cols = ['Previous_Accident_Flag', 'Previous_Speeding_Flag']

for col in history_cols:
    numeric_values = pd.to_numeric(vehicle_person[col], errors='coerce')
    vehicle_person[col] = numeric_values.fillna(0).astype(int)

driver_subset = vehicle_person[vehicle_person['Seat_Category'] == 'Driver'].copy()

driver_history_features = driver_subset.groupby('Crash_ID').agg(
    Driver_License_Category=('Driver_License_Category', 'first'),
    Driver_Max_Prev_Accident_Count=('Previous_Accident_Flag', 'max'),
    Driver_Max_Prev_Speeding_Count=('Previous_Speeding_Flag', 'max')
).reset_index()

total_killed_alive = total_killed_alive.merge(
    driver_history_features, 
    on='Crash_ID', 
    how='left'
)

In [49]:
total_killed_alive.head(10)

,Crash_ID,Total_Killed,Total_Alive,Fatal_Seats_List,Killed_Restraint_List,Any_Driver_Drinking,Total_Drinking_Drivers,Driver_License_Category,Driver_Max_Prev_Accident_Count,Driver_Max_Prev_Speeding_Count
0,10001,1,0,[Driver],[Shoulder_Lapbelt],0,0,Valid,0.0,1.0
1,10002,1,0,[Driver],[None_Used],1,1,Valid,0.0,0.0
2,10003,1,0,[Driver],[None_Used],1,1,Valid,0.0,0.0
3,10004,1,2,[Rear_Seat],[None_Used],1,1,Valid,1.0,0.0
4,10005,1,3,[Driver],[Shoulder_Lapbelt],0,0,Invalid,0.0,0.0
5,10006,1,0,[Driver],[Shoulder_Lapbelt],0,0,Valid,4.0,0.0
6,10007,2,0,"[Driver, Driver]","[None_Used, None_Used]",0,0,Valid,0.0,1.0
7,10008,1,1,[Front_Passenger],[None_Used],0,0,Invalid,2.0,1.0
8,10009,2,1,"[Front_Passenger, Rear_Seat]","[None_Used, None_Used]",1,1,Invalid,0.0,1.0
9,10010,1,3,[Driver],[Shoulder_Lapbelt],1,2,Valid,0.0,1.0

In [50]:
driver_subset = vehicle_person[vehicle_person['Seat_Category'] == 'Driver'].copy()
driver_features = driver_subset.groupby('Crash_ID').agg(
    Max_Driver_Age=('Age', 'max'),
    Min_Driver_Age=('Age', 'min'),
    Driver_Sex_List=('Sex', lambda x: x.tolist())
).reset_index()
total_killed_alive = total_killed_alive.merge(
    driver_features, 
    on='Crash_ID', 
    how='left'
)

In [51]:
vehicle_person['Speed_Related_Flag'].unique()

array(['No', 'Yes, Exceeded Speed Limit', 'Yes, Too Fast for Conditions',
       'Reported as Unknown',
       'No Driver Present/Unknown if Driver Present',
       'Yes, Specifics Unknown', 'Yes, Racing'], dtype=object)

In [52]:
#Speeding
def categorize_speeding(status):
    if pd.isna(status):
        return 'No'
    
    status_std = str(status).strip().upper()

    if status_std == 'NO':
        return 'No'
    elif 'YES' in status_std or 'RACING' in status_std:
        return 'Yes'
    elif 'TOO FAST FOR CONDITIONS' in status_std:
        return 'Too Fast' 
    else:
        return 'No'

vehicle_person['Speeding_Status_Category'] = vehicle_person['Speed_Related_Flag'].apply(categorize_speeding)
vehicle_person = vehicle_person.drop(columns=['Speed_Related_Flag'])

def is_exceeding_limit(status):
    category = categorize_speeding(status)
    return 1 if category == 'Yes' else 0

def is_too_fast_for_conditions(status):
    category = categorize_speeding(status)
    return 1 if category == 'Too Fast' else 0

vehicle_person['Is_Exceeding_Limit'] = vehicle_person['Speeding_Status_Category'].apply(is_exceeding_limit)
vehicle_person['Is_Too_Fast'] = vehicle_person['Speeding_Status_Category'].apply(is_too_fast_for_conditions)

speeding_counts_agg = vehicle_person.groupby('Crash_ID').agg(
    Total_Exceeding_Limit_Vehicles=('Is_Exceeding_Limit', 'sum'),
    Total_Too_Fast_Vehicles=('Is_Too_Fast', 'sum')
).reset_index()

total_killed_alive = total_killed_alive.merge(
    speeding_counts_agg, 
    on='Crash_ID', 
    how='left'
)

In [53]:
print(vehicle_person['Vehicle_Body_Type'].unique())
print(vehicle_person['Vehicle_Damage_Extent'].unique())
print(vehicle_person['First_Harmful_Event'].unique())

['Sport Utility Vehicle (SUV)/Multi-Purpose Vehicle (MPV)'
 'Hatchback/Liftback/Notchback' 'Sedan/Saloon' 'Pickup'
 'Sport Utility Truck (SUT)' 'Coupe' 'Cargo Van'
 'Off-road Vehicle - All Terrain Vehicle (ATV) (Motorcycle-style)'
 'Motorcycle - Sport' 'Motorcycle - Street' 'Incomplete - Cutaway'
 'Motorcycle - Touring / Sport Touring' 'Truck-Tractor'
 'Motorcycle - Standard' 'Convertible/Cabriolet' 'Unknown' 'Minivan'
 'Truck' 'Incomplete - Glider' 'Van' 'Crossover Utility Vehicle (CUV)'
 'Motorcycle - Cruiser' 'Incomplete - Chassis Cab (Single Cab)' 'Bus'
 'Incomplete' 'Motorcycle - Custom' 'Incomplete - School Bus Chassis'
 'Off-road Vehicle - Motocross (Off-road short distance, closed track racing)'
 'Incomplete - Chassis Cab (Number of Cab Unknown)' 'Other'
 'Motorcycle - Trike' 'Incomplete - Chassis Cab (Double Cab)' 'Wagon'
 'Off-road Vehicle - Recreational Off-Road Vehicle (ROV)'
 'Motorcycle - Unenclosed Three Wheeled / Open Autocycle'
 'Motorcycle - Unknown Body Class'
 'Off-road Vehicle - Enduro (Off-road long distance racing)'
 'Bus - School Bus' 'Incomplete - Commercial Chassis'
 'Incomplete - Motor Home Chassis'
 'Motorcycle - Dual Sport / Adventure / Supermoto / On/Off-road'
 'Off-road Vehicle - Dirt Bike / Off-Road' 'Motorcycle - Scooter'
 'Not Reported' 'Off-road Vehicle - Construction Equipment'
 'Off-road Vehicle - Farm Equipment' 'Off-road Vehicle - Golf Cart'
 'Motorcycle - Moped' 'Step Van / Walk-in Van'
 'Off-road Vehicle - Go Kart' 'Fire Apparatus'
 'Motorcycle - Small / Minibike' 'Roadster' 'Motorhome'
 'Incomplete - Stripped Chassis' 'Motorcycle - Underbone' 'Street Sweeper'
 'Low Speed Vehicle (LSV) / Neighborhood Electric Vehicle (NEV)'
 'Motorcycle - Side Car' 'Motorcycle - Cross Country'
 'Off-road Vehicle - Snowmobile' 'Incomplete - Bus Chassis']
['Disabling Damage' 'Minor Damage' 'Functional Damage'
 'Reported as Unknown' 'No Damage' 'Not Reported'
 'Damage Reported, Extent Unknown']
['Embankment' 'Tree (Standing Only)' 'Rollover/Overturn'
 'Motor Vehicle In-Transport' 'Culvert' 'Fire/Explosion' 'Pedestrian'
 'Boulder' 'Ditch' 'Building' 'Railway Vehicle'
 'Motor Vehicle In-Transport Strikes or is Struck by Cargo, Persons or Objects Set-in-Motion from/by Another Motor Vehicle In Transport'
 'Wall' 'Parked Motor Vehicle' 'Bridge Pier or Support'
 'Utility Pole/Light Support' 'Pedalcyclist' 'Other Fixed Object' 'Curb'
 'Guardrail Face' 'Traffic Sign Support' 'Concrete Traffic Barrier'
 'Non-Motorist on Personal Conveyance' 'Mail Box'
 'Bridge Rail (Includes parapet)' 'Other Object (not fixed)'
 'Immersion or Partial Immersion' 'Guardrail End' 'Live Animal'
 'Unknown Fixed Object' 'Fence'
 'Cargo/Equipment Loss, Shift, or Damage [harmful]'
 'Working Motor Vehicle'
 'Object That Had Fallen From Motor Vehicle In-Transport'
 'Fell/Jumped from Vehicle' 'Post, Pole or Other Supports'
 'Harmful Event, Details Not Reported' 'Traffic Signal Support'
 'Impact Attenuator/Crash Cushion'
 'Pavement Surface Irregularity (Ruts, Potholes, Grates, etc.)'
 'Reported as Unknown' 'Shrubbery' 'Jackknife (harmful to this vehicle)'
 'Other Non-Collision' 'Cable Barrier' 'Ground' 'Unknown Object Not Fixed'
 'Road Vehicle on Rails' 'Thrown or Falling Object' 'Fire Hydrant'
 'Ridden Animal or Animal Drawn Conveyance' 'Other Traffic Barrier'
 'Injured In Vehicle (Non-Collision)' 'Bridge Overhead Structure'
 'Gas Inhalation' 'Motor Vehicle in Motion Outside the Trafficway'
 'Snow Bank']

In [54]:
body_type_to_rank_map = {
    # Rank 5: Motorcycle/Off-Road (Highest Risk)
    'Motorcycle - Sport': 5, 'Motorcycle - Street': 5, 'Motorcycle - Touring / Sport Touring': 5, 
    'Motorcycle - Standard': 5, 'Motorcycle - Cruiser': 5, 'Motorcycle - Custom': 5, 
    'Motorcycle - Trike': 5, 'Motorcycle - Unenclosed Three Wheeled / Open Autocycle': 5, 
    'Motorcycle - Unknown Body Class': 5, 'Motorcycle - Dual Sport / Adventure / Supermoto / On/Off-road': 5, 
    'Motorcycle - Scooter': 5, 'Motorcycle - Moped': 5, 'Motorcycle - Small / Minibike': 5, 
    'Motorcycle - Underbone': 5, 'Motorcycle - Side Car': 5, 'Motorcycle - Cross Country': 5, 
    'Off-road Vehicle - All Terrain Vehicle (ATV) (Motorcycle-style)': 5,
    'Off-road Vehicle - Motocross (Off-road short distance, closed track racing)': 5,
    'Off-road Vehicle - Recreational Off-Road Vehicle (ROV)': 5, 'Off-road Vehicle - Enduro (Off-road long distance racing)': 5,
    'Off-road Vehicle - Dirt Bike / Off-Road': 5, 'Off-road Vehicle - Construction Equipment': 5,
    'Off-road Vehicle - Farm Equipment': 5, 'Off-road Vehicle - Golf Cart': 5, 'Off-road Vehicle - Go Kart': 5,
    'Off-road Vehicle - Snowmobile': 5,
    
    # Rank 4: Truck-Tractor/Bus
    'Truck-Tractor': 4, 'Truck': 4, 'Bus': 4, 'Bus - School Bus': 4,
    
    # Rank 3: Trucks/Large SUV/Van
    'Pickup': 3, 'Sport Utility Truck (SUT)': 3, 'Cargo Van': 3, 'Van': 3, 'Step Van / Walk-in Van': 3,
    'Sport Utility Vehicle (SUV)/Multi-Purpose Vehicle (MPV)': 3, 'Minivan': 3, 'Crossover Utility Vehicle (CUV)': 3,

    # Rank 2: Standard Passenger/Specialty
    'Hatchback/Liftback/Notchback': 2, 'Sedan/Saloon': 2, 'Coupe': 2, 'Convertible/Cabriolet': 2, 'Wagon': 2, 'Roadster': 2,
    'Motorhome': 2, 'Fire Apparatus': 2, 'Street Sweeper': 2, 'Low Speed Vehicle (LSV) / Neighborhood Electric Vehicle (NEV)': 2,
    
    # Rank 1: Unknown/Other/Niche/Incomplete
    'Unknown': 1, 'Other': 1, 'Not Reported': 1,
    'Incomplete - Cutaway': 1, 'Incomplete - Glider': 1, 'Incomplete - Chassis Cab (Single Cab)': 1, 
    'Incomplete': 1, 'Incomplete - School Bus Chassis': 1, 'Incomplete - Chassis Cab (Number of Cab Unknown)': 1,
    'Incomplete - Chassis Cab (Double Cab)': 1, 'Incomplete - Commercial Chassis': 1, 
    'Incomplete - Motor Home Chassis': 1, 'Incomplete - Stripped Chassis': 1, 'Incomplete - Bus Chassis': 1,
}

vehicle_person['Vehicle_Type_Severity_Rank'] = vehicle_person['Vehicle_Body_Type'].map(body_type_to_rank_map)

vehicle_type_agg = vehicle_person.groupby('Crash_ID').agg(
    Max_Vehicle_Type_Severity_5=('Vehicle_Type_Severity_Rank', 'max')
).reset_index()

total_killed_alive = total_killed_alive.merge(
    vehicle_type_agg, 
    on='Crash_ID', 
    how='left'
)

In [55]:
damage_to_rank_map = {
    'Disabling Damage': 4,
    'Functional Damage': 3,
    'Minor Damage': 2,
    'No Damage': 1,
    'Reported as Unknown': 0,
    'Not Reported': 0,
    'Damage Reported, Extent Unknown': 1
}

vehicle_person['Damage_Severity_Rank'] = vehicle_person['Vehicle_Damage_Extent'].map(damage_to_rank_map).fillna(0).astype(int)

damage_agg = vehicle_person.groupby('Crash_ID').agg(
    Max_Vehicle_Damage_Rank=('Damage_Severity_Rank', 'max')
).reset_index()

total_killed_alive = total_killed_alive.merge(
    damage_agg, 
    on='Crash_ID', 
    how='left'
)

In [56]:
event_to_rank_map = {
    # Rank 5: Vehicle-to-Vehicle - Highest Total Fatalities Risk 
    'Fire/Explosion': 3, 'Motor Vehicle In-Transport': 5, 'Motor Vehicle In-Transport Strikes or is Struck by Cargo, Persons or Objects Set-in-Motion from/by Another Motor Vehicle In Transport': 5, 
    'Parked Motor Vehicle': 5, 'Working Motor Vehicle': 5, 'Motor Vehicle in Motion Outside the Trafficway': 5,

    # Rank 4: Vulnerable Users / Water / Rail
    'Pedestrian': 4, 'Pedalcyclist': 4, 'Non-Motorist on Personal Conveyance': 4,
    'Immersion or Partial Immersion': 4, 'Railway Vehicle': 4, 'Road Vehicle on Rails': 4,
    
    # Rank 3: Fixed Object / Rollover 
    'Rollover/Overturn': 3, 'Tree (Standing Only)': 3, 'Culvert': 3, 'Building': 3, 'Wall': 3, 
    'Bridge Pier or Support': 3, 'Utility Pole/Light Support': 3, 'Traffic Sign Support': 3, 
    'Concrete Traffic Barrier': 3, 'Bridge Rail (Includes parapet)': 3, 'Guardrail End': 3, 
    'Unknown Fixed Object': 3, 'Post, Pole or Other Supports': 3, 'Traffic Signal Support': 3, 
    'Impact Attenuator/Crash Cushion': 3, 'Fire Hydrant': 3, 'Bridge Overhead Structure': 3, 
    'Cable Barrier': 3,  
    
    # Rank 2: General/Other Objects 
    'Embankment': 2, 'Boulder': 2, 'Ditch': 2, 'Other Fixed Object': 2, 'Curb': 2, 
    'Guardrail Face': 2, 'Mail Box': 2, 'Other Object (not fixed)': 2, 'Fence': 2, 
    'Pavement Surface Irregularity (Ruts, Potholes, Grates, etc.)': 2, 'Shrubbery': 2, 
    'Ground': 2, 'Snow Bank': 2,

    # Rank 1: Non-Collision / Unknown 
    'Live Animal': 1, 'Cargo/Equipment Loss, Shift, or Damage [harmful]': 1, 
    'Object That Had Fallen From Motor Vehicle In-Transport': 1, 'Fell/Jumped from Vehicle': 1, 
    'Harmful Event, Details Not Reported': 1, 'Reported as Unknown': 1, 'Other Non-Collision': 1, 
    'Unknown Object Not Fixed': 1, 'Thrown or Falling Object': 1, 'Ridden Animal or Animal Drawn Conveyance': 1, 
    'Injured In Vehicle (Non-Collision)': 1, 'Gas Inhalation': 1, 'Jackknife (harmful to this vehicle)': 1
}

vehicle_person['Harmful_Event_Severity_Rank'] = vehicle_person['First_Harmful_Event'].map(event_to_rank_map).fillna(0).astype(int)

event_agg = vehicle_person.groupby('Crash_ID').agg(
    Max_Harmful_Event_Severity=('Harmful_Event_Severity_Rank', 'max')
).reset_index()

total_killed_alive = total_killed_alive.merge(
    event_agg, 
    on='Crash_ID', 
    how='left'
)

In [57]:
total_killed_alive.head(10)

,Crash_ID,Total_Killed,Total_Alive,Fatal_Seats_List,Killed_Restraint_List,Any_Driver_Drinking,Total_Drinking_Drivers,Driver_License_Category,Driver_Max_Prev_Accident_Count,Driver_Max_Prev_Speeding_Count,Max_Driver_Age,Min_Driver_Age,Driver_Sex_List,Total_Exceeding_Limit_Vehicles,Total_Too_Fast_Vehicles,Max_Vehicle_Type_Severity_5,Max_Vehicle_Damage_Rank,Max_Harmful_Event_Severity
0,10001,1,0,[Driver],[Shoulder_Lapbelt],0,0,Valid,0.0,1.0,33.0,33.0,[Male],0,0,3,4,2
1,10002,1,0,[Driver],[None_Used],1,1,Valid,0.0,0.0,32.0,32.0,[Female],0,0,2,4,3
2,10003,1,0,[Driver],[None_Used],1,1,Valid,0.0,0.0,21.0,21.0,[Female],1,0,2,4,3
3,10004,1,2,[Rear_Seat],[None_Used],1,1,Valid,1.0,0.0,54.0,54.0,[Male],3,0,3,4,3
4,10005,1,3,[Driver],[Shoulder_Lapbelt],0,0,Invalid,0.0,0.0,54.0,54.0,[Male],4,0,2,4,3
5,10006,1,0,[Driver],[Shoulder_Lapbelt],0,0,Valid,4.0,0.0,67.0,67.0,[Male],0,0,3,4,3
6,10007,2,0,"[Driver, Driver]","[None_Used, None_Used]",0,0,Valid,0.0,1.0,46.0,33.0,"[Male, Male]",0,0,3,4,5
7,10008,1,1,[Front_Passenger],[None_Used],0,0,Invalid,2.0,1.0,34.0,34.0,[Male],0,0,3,4,3
8,10009,2,1,"[Front_Passenger, Rear_Seat]","[None_Used, None_Used]",1,1,Invalid,0.0,1.0,28.0,28.0,[Male],0,0,2,4,3
9,10010,1,3,[Driver],[Shoulder_Lapbelt],1,2,Valid,0.0,1.0,33.0,33.0,"[Male, Male]",0,0,3,4,5

In [58]:
vehicle_person.columns

Index(['Crash_ID', 'Vehicle_ID', 'State_Name', 'Injury_Severity',
       'Time_to_Death_Hours', 'Time_to_Death_Minutes', 'Age', 'Sex',
       'Num_Occupants', 'Previous_Accident_Flag', 'Previous_Speeding_Flag',
       'Vehicle_Body_Type', 'Vehicle_Damage_Extent', 'First_Harmful_Event',
       'Travel_Speed_Limit', 'Road_Surface_Condition',
       'Road_Horizontal_Alignment', 'Road_Vertical_Profile', 'Is_Killed',
       'Is_Alive', 'Seat_Category', 'Killed_Seat_Position',
       'Restraint_Category', 'Killed_Restraint_Status',
       'Is_Drinking_Driver_Flag', 'License_Category',
       'Driver_License_Category', 'Speeding_Status_Category',
       'Is_Exceeding_Limit', 'Is_Too_Fast', 'Vehicle_Type_Severity_Rank',
       'Damage_Severity_Rank', 'Harmful_Event_Severity_Rank'],
      dtype='object')

In [59]:
print(vehicle_person['Road_Surface_Condition'].unique())
print(vehicle_person['Road_Horizontal_Alignment'].unique())
print(vehicle_person['Road_Vertical_Profile'].unique())

['Dry' 'Wet' 'Non-Trafficway or Driveway Access' 'Reported as Unknown'
 'Mud, Dirt or Gravel' 'Slush' 'Not Reported' 'Snow' 'Ice/Frost'
 'Water (Standing or Moving)' 'Other' 'Sand' 'Oil']
['Straight' 'Curve - Right' 'Curve - Left'
 'Non-Trafficway or Driveway Access' 'Not Reported' 'Reported as Unknown'
 'Curve - Unknown Direction']
['Downhill' 'Level' 'Uphill' 'Non-Trafficway or Driveway Access'
 'Hillcrest' 'Not Reported' 'Grade, Unknown Slope' 'Reported as Unknown'
 'Sag (Bottom)']

In [60]:
surface_categorization_map = {
    # Icy/Snowy
    'Ice/Frost': 'Icy/Snowy', 
    'Snow': 'Icy/Snowy', 
    'Slush': 'Icy/Snowy',
    
    # Wet/Standing Water
    'Wet': 'Wet/Standing Water', 
    'Water (Standing or Moving)': 'Wet/Standing Water',
    
    # Loose/Unpaved
    'Mud, Dirt or Gravel': 'Loose/Unpaved', 
    'Sand': 'Loose/Unpaved',
    
    # Oil/Contaminated
    'Oil': 'Oil/Contaminated', 
    'Other': 'Oil/Contaminated',
    
    # Dry
    'Dry': 'Dry', 
    'Non-Trafficway or Driveway Access': 'Dry', 

    # Unknown
    'Reported as Unknown': 'Dry', 
    'Not Reported': 'Dry',
}

vehicle_person['Road_Surface_Category'] = vehicle_person['Road_Surface_Condition'].map(surface_categorization_map).fillna('Unknown')

surface_agg = vehicle_person.groupby('Crash_ID').agg(
    Crash_Road_Surface_Condition=('Road_Surface_Category', 'first')
).reset_index()

total_killed_alive = total_killed_alive.merge(
    surface_agg[['Crash_ID', 'Crash_Road_Surface_Condition']], 
    on='Crash_ID', 
    how='left'
)

In [61]:
vehicle_person = vehicle_person.drop(columns=['Road_Surface_Condition'])

In [62]:
alignment_categorization_map = {
    'Straight': 'Straight',
    'Curve - Right': 'Curve',
    'Curve - Left': 'Curve',
    'Curve - Unknown Direction': 'Curve',
    'Non-Trafficway or Driveway Access': 'Straight',
    'Not Reported': 'Straight',
    'Reported as Unknown': 'Straight',
}

vehicle_person['Horizontal_Alignment_Category'] = vehicle_person['Road_Horizontal_Alignment'].map(alignment_categorization_map).fillna('Unknown')

alignment_agg = vehicle_person.groupby('Crash_ID').agg(
    Crash_Horizontal_Alignment=('Horizontal_Alignment_Category', 'first')
).reset_index()

total_killed_alive = total_killed_alive.merge(
    alignment_agg[['Crash_ID', 'Crash_Horizontal_Alignment']], 
    on='Crash_ID', 
    how='left'
)

vehicle_person = vehicle_person.drop(columns=['Road_Horizontal_Alignment'], errors='ignore')

In [63]:
profile_categorization_map = {
    'Downhill': 'Grade/Hillcrest',
    'Uphill': 'Grade/Hillcrest',
    'Hillcrest': 'Grade/Hillcrest',
    'Sag (Bottom)': 'Grade/Hillcrest',
    'Level': 'Level',
    'Non-Trafficway or Driveway Access': 'Non-Trafficway',
    'Not Reported': 'Level',
    'Reported as Unknown': 'Level',
    'Grade, Unknown Slope': 'Grade/Hillcrest',
}

vehicle_person['Vertical_Profile_Category'] = vehicle_person['Road_Vertical_Profile'].map(profile_categorization_map).fillna('Unknown')

profile_agg = vehicle_person.groupby('Crash_ID').agg(
    Crash_Vertical_Profile=('Vertical_Profile_Category', 'first')
).reset_index()

total_killed_alive = total_killed_alive.merge(
    profile_agg[['Crash_ID', 'Crash_Vertical_Profile']], 
    on='Crash_ID', 
    how='left'
)

vehicle_person = vehicle_person.drop(columns=['Road_Vertical_Profile'], errors='ignore')

In [64]:
total_killed_alive.head(10)

,Crash_ID,Total_Killed,Total_Alive,Fatal_Seats_List,Killed_Restraint_List,Any_Driver_Drinking,Total_Drinking_Drivers,Driver_License_Category,Driver_Max_Prev_Accident_Count,Driver_Max_Prev_Speeding_Count,...,Min_Driver_Age,Driver_Sex_List,Total_Exceeding_Limit_Vehicles,Total_Too_Fast_Vehicles,Max_Vehicle_Type_Severity_5,Max_Vehicle_Damage_Rank,Max_Harmful_Event_Severity,Crash_Road_Surface_Condition,Crash_Horizontal_Alignment,Crash_Vertical_Profile
0,10001,1,0,[Driver],[Shoulder_Lapbelt],0,0,Valid,0.0,1.0,...,33.0,[Male],0,0,3,4,2,Dry,Straight,Grade/Hillcrest
1,10002,1,0,[Driver],[None_Used],1,1,Valid,0.0,0.0,...,32.0,[Female],0,0,2,4,3,Dry,Straight,Level
2,10003,1,0,[Driver],[None_Used],1,1,Valid,0.0,0.0,...,21.0,[Female],1,0,2,4,3,Dry,Curve,Grade/Hillcrest
3,10004,1,2,[Rear_Seat],[None_Used],1,1,Valid,1.0,0.0,...,54.0,[Male],3,0,3,4,3,Dry,Curve,Grade/Hillcrest
4,10005,1,3,[Driver],[Shoulder_Lapbelt],0,0,Invalid,0.0,0.0,...,54.0,[Male],4,0,2,4,3,Wet/Standing Water,Straight,Level
5,10006,1,0,[Driver],[Shoulder_Lapbelt],0,0,Valid,4.0,0.0,...,67.0,[Male],0,0,3,4,3,Dry,Straight,Level
6,10007,2,0,"[Driver, Driver]","[None_Used, None_Used]",0,0,Valid,0.0,1.0,...,33.0,"[Male, Male]",0,0,3,4,5,Dry,Curve,Level
7,10008,1,1,[Front_Passenger],[None_Used],0,0,Invalid,2.0,1.0,...,34.0,[Male],0,0,3,4,3,Dry,Curve,Grade/Hillcrest
8,10009,2,1,"[Front_Passenger, Rear_Seat]","[None_Used, None_Used]",1,1,Invalid,0.0,1.0,...,28.0,[Male],0,0,2,4,3,Dry,Straight,Grade/Hillcrest
9,10010,1,3,[Driver],[Shoulder_Lapbelt],1,2,Valid,0.0,1.0,...,33.0,"[Male, Male]",0,0,3,4,5,Dry,Curve,Level

In [65]:
len(data['ST_CASE'].unique())
print(data.columns)

Index(['STATE', 'STATENAME', 'ST_CASE', 'PERNOTMVIT', 'VE_TOTAL', 'VE_FORMS',
       'PVH_INVL', 'PERMVIT', 'CITYNAME', 'MONTHNAME', 'DAYNAME',
       'DAY_WEEKNAME', 'HOUR', 'MINUTE', 'RUR_URBNAME', 'FUNC_SYSNAME',
       'NHSNAME', 'LATITUDE', 'LONGITUD', 'HARM_EVNAME', 'TYP_INTNAME',
       'LGT_CONDNAME', 'WEATHERNAME', 'NOT_HOURNAME', 'NOT_MINNAME',
       'ARR_HOURNAME', 'ARR_MINNAME', 'HOSP_HRNAME', 'HOSP_MNNAME', 'FATALS'],
      dtype='object')

In [66]:
print(total_killed_alive.columns)

Index(['Crash_ID', 'Total_Killed', 'Total_Alive', 'Fatal_Seats_List',
       'Killed_Restraint_List', 'Any_Driver_Drinking',
       'Total_Drinking_Drivers', 'Driver_License_Category',
       'Driver_Max_Prev_Accident_Count', 'Driver_Max_Prev_Speeding_Count',
       'Max_Driver_Age', 'Min_Driver_Age', 'Driver_Sex_List',
       'Total_Exceeding_Limit_Vehicles', 'Total_Too_Fast_Vehicles',
       'Max_Vehicle_Type_Severity_5', 'Max_Vehicle_Damage_Rank',
       'Max_Harmful_Event_Severity', 'Crash_Road_Surface_Condition',
       'Crash_Horizontal_Alignment', 'Crash_Vertical_Profile'],
      dtype='object')

In [67]:
data.rename(columns={
    'ST_CASE': 'Crash_ID',
    'STATE': 'State_Code',
    'STATENAME': 'State_Name',
    'PERNOTMVIT': 'Count_Non_Motorists',
    'VE_TOTAL': 'Count_Vehicles_Total',
    'VE_FORMS': 'Count_Vehicle_Forms',
    'PVH_INVL': 'Count_PVH_Involved',
    'PERMVIT': 'Count_Occupants_MV',
    'CITYNAME': 'City_Name',
    'MONTHNAME': 'Month_Name',
    'DAYNAME': 'Day_of_Month',
    'DAY_WEEKNAME': 'Day_of_Week',
    'HOUR': 'Crash_Hour',
    'MINUTE': 'Crash_Minute',
    'RUR_URBNAME': 'Area_Rural_Urban',
    'FUNC_SYSNAME': 'Road_Functional_Class',
    'NHSNAME': 'On_NHS_Road',
    'LATITUDE': 'Latitude',
    'LONGITUD': 'Longitude',
    'HARM_EVNAME': 'First_Harmful_Event_Raw', 
    'TYP_INTNAME': 'Intersection_Type',
    'LGT_CONDNAME': 'Light_Condition',
    'WEATHERNAME': 'Weather_Condition',
    'NOT_HOURNAME': 'Notif_Hour',
    'NOT_MINNAME': 'Notif_Minute',
    'ARR_HOURNAME': 'Arrival_Hour',
    'ARR_MINNAME': 'Arrival_Minute',
    'HOSP_HRNAME': 'Hospital_Hour',
    'HOSP_MNNAME': 'Hospital_Minute',
    'FATALS': 'Fatalities_Count'
}, inplace=True)

In [68]:
data = data.drop(columns=['First_Harmful_Event_Raw'])

In [69]:
print(data['Area_Rural_Urban'].unique())
print(data['Road_Functional_Class'].unique())
print(data['On_NHS_Road'].unique())
print(data['Intersection_Type'].unique())

['Rural' 'Urban' 'Trafficway Not in State Inventory' 'Unknown'
 'Not Reported']
['Major Collector' 'Local' 'Interstate' 'Other Principal Arterial'
 'Minor Arterial' 'Other Freeways and Expressways' 'Minor Collector'
 'Trafficway Not in State Inventory' 'Unknown' 'Not Reported']
['This Section IS NOT on the NHS' 'This Section IS ON the NHS'
 'Unknown if This Section Is on the NHS']
['Not an Intersection' 'Four-Way Intersection' 'T-Intersection'
 'Traffic Circle' 'Y-Intersection' 'Not Reported' 'Reported as Unknown'
 'Roundabout' 'Five Point, or More' 'L-Intersection'
 'Other Intersection Type']

In [70]:
area_categorization_map = {
    'Rural': 'Rural',
    'Urban': 'Urban',
    'Trafficway Not in State Inventory': 'Rural', 
    'Not Reported': 'Rural',
    'Unknown': 'Rural',
}
data['Area_Rural_Urban'] = data['Area_Rural_Urban'].map(area_categorization_map).fillna('Rural') 

functional_class_map = {
    'Interstate': 'High Speed (Arterial)',
    'Other Principal Arterial': 'High Speed (Arterial)',
    'Other Freeways and Expressways': 'High Speed (Arterial)',
    'Major Collector': 'Medium Speed (Collector)',
    'Minor Arterial': 'Medium Speed (Collector)',
    'Minor Collector': 'Medium Speed (Collector)',
    'Local': 'Low Speed (Local)',
    'Trafficway Not in State Inventory': 'Low Speed (Local)',
    'Unknown': 'Low Speed (Local)',
    'Not Reported': 'Low Speed (Local)',
}
data['Road_Functional_Class'] = data['Road_Functional_Class'].map(functional_class_map).fillna('Low Speed (Local)')

nhs_map = {
    'This Section IS ON the NHS': 'Yes',
    'This Section IS NOT on the NHS': 'No',
    'Unknown if This Section Is on the NHS': 'No',
}
data['On_NHS_Road'] = data['On_NHS_Road'].map(nhs_map).fillna('No')

intersection_map_final = {
    'Not an Intersection': 'Non-Intersection',
    'Not Reported': 'Non-Intersection', 
    'Reported as Unknown': 'Non-Intersection',
    'T-Intersection': 'Simple Junction',
    'Y-Intersection': 'Simple Junction',
    'L-Intersection': 'Simple Junction',
    'Four-Way Intersection': 'Complex/Circle', 
    'Traffic Circle': 'Complex/Circle',
    'Roundabout': 'Complex/Circle',
    'Five Point, or More': 'Complex/Circle',
    'Other Intersection Type': 'Complex/Circle',
}
data['Intersection_Type'] = data['Intersection_Type'].map(intersection_map_final).fillna('Non-Intersection')

In [71]:
print(data['Light_Condition'].unique())
print(data['Weather_Condition'].unique())

['Dark - Not Lighted' 'Daylight' 'Dark - Lighted' 'Dusk'
 'Dark - Unknown Lighting' 'Dawn' 'Reported as Unknown' 'Not Reported'
 'Other']
['Clear' 'Rain' 'Cloudy' 'Fog, Smog, Smoke' 'Reported as Unknown'
 'Not Reported' 'Snow' 'Other' 'Freezing Rain or Drizzle'
 'Severe Crosswinds' 'Blowing Sand, Soil, Dirt' 'Sleet or Hail'
 'Blowing Snow']

In [72]:
light_map = {
    'Daylight': 'Daylight',
    'Dark - Lighted': 'Dark - Lighted',
    'Dusk': 'Twilight',
    'Dawn': 'Twilight',
    'Dark - Not Lighted': 'Dark - Unlighted', 
    'Dark - Unknown Lighting': 'Dark - Unlighted',
    'Reported as Unknown': 'Dark - Unlighted',
    'Not Reported': 'Dark - Unlighted',
    'Other': 'Dark - Unlighted',
}
data['Clean_Light_Condition'] = data['Light_Condition'].map(light_map).fillna('Dark - Unlighted')

weather_map = {
    'Clear': 'Clear',
    'Reported as Unknown': 'Clear',
    'Not Reported': 'Clear',
    'Cloudy': 'Reduced Visibility',
    'Fog, Smog, Smoke': 'Reduced Visibility',
    'Other': 'Reduced Visibility',
    'Rain': 'Rain/Wind/Minor',
    'Severe Crosswinds': 'Rain/Wind/Minor',
    'Blowing Sand, Soil, Dirt': 'Rain/Wind/Minor',
    'Snow': 'Snow/Ice/Severe',
    'Freezing Rain or Drizzle': 'Snow/Ice/Severe',
    'Sleet or Hail': 'Snow/Ice/Severe',
    'Blowing Snow': 'Snow/Ice/Severe',
}
data['Clean_Weather_Condition'] = data['Weather_Condition'].map(weather_map).fillna('Clear')

In [73]:
data = data.merge(
    total_killed_alive, 
    on='Crash_ID', 
    how='left'
)

In [74]:
data.columns

Index(['State_Code', 'State_Name', 'Crash_ID', 'Count_Non_Motorists',
       'Count_Vehicles_Total', 'Count_Vehicle_Forms', 'Count_PVH_Involved',
       'Count_Occupants_MV', 'City_Name', 'Month_Name', 'Day_of_Month',
       'Day_of_Week', 'Crash_Hour', 'Crash_Minute', 'Area_Rural_Urban',
       'Road_Functional_Class', 'On_NHS_Road', 'Latitude', 'Longitude',
       'Intersection_Type', 'Light_Condition', 'Weather_Condition',
       'Notif_Hour', 'Notif_Minute', 'Arrival_Hour', 'Arrival_Minute',
       'Hospital_Hour', 'Hospital_Minute', 'Fatalities_Count',
       'Clean_Light_Condition', 'Clean_Weather_Condition', 'Total_Killed',
       'Total_Alive', 'Fatal_Seats_List', 'Killed_Restraint_List',
       'Any_Driver_Drinking', 'Total_Drinking_Drivers',
       'Driver_License_Category', 'Driver_Max_Prev_Accident_Count',
       'Driver_Max_Prev_Speeding_Count', 'Max_Driver_Age', 'Min_Driver_Age',
       'Driver_Sex_List', 'Total_Exceeding_Limit_Vehicles',
       'Total_Too_Fast_Vehicles', 'Max_Vehicle_Type_Severity_5',
       'Max_Vehicle_Damage_Rank', 'Max_Harmful_Event_Severity',
       'Crash_Road_Surface_Condition', 'Crash_Horizontal_Alignment',
       'Crash_Vertical_Profile'],
      dtype='object')

In [75]:
driver_impairment = pd.read_csv(r'C:\DATA ANALYSIS AND DATA SCIENCE PROJECTS\Accident Severity Prediction\data\raw data files\drimpair.csv')
driver_impairment.columns
driver_impairment = driver_impairment[['ST_CASE', 'DRIMPAIRNAME']].copy()
driver_impairment.rename(columns={
    'ST_CASE': 'Crash_ID', 
    'DRIMPAIRNAME': 'Driver_Impairment_Description'
}, inplace = 'True')

impairment_risk_map = {
    # Highest Risk (3)
    'Under the Influence of Alcohol, Drugs, or Medication': 3,
    'Emotional (Depressed, Angry, Disturbed, etc.)': 3,
    'Blind/Low Vision': 3,

    # Medium Risk (2)
    'Asleep or Fatigued': 2,
    'Impaired Due to Previous Injury': 2,
    'Ill, Blackout': 2, 

    # Lowest/Baseline Risk (1) - Includes all Unknowns/Physical Impairments
    'None/Apparently Normal': 1,
    'Physical Impairment - No Details': 1,
    'Deaf/Hard of Hearing': 1,
    'Paraplegic or Restricted to Wheelchair': 1,
    'Paraplegic or in a Wheelchair': 1,
    'Walking With a Cane or Crutches, etc.': 1,
    'Other Physical Impairment': 1,
    'No Driver Present/Unknown if Driver Present': 1,
    'Not Reported': 1,
    'Unknown if Impaired': 1,
    'Reported as Unknown as Impaired': 1
}
driver_impairment['Impairment_Risk'] = driver_impairment['Driver_Impairment_Description'].map(impairment_risk_map).fillna(1) 

impairment_agg = driver_impairment.groupby('Crash_ID').agg(
    Max_Driver_Impairment_Severity=('Impairment_Risk', 'max')
).reset_index()

final_risk_map_inverse = {
    3: 'Highest',
    2: 'Medium',
    1: 'Lowest'
}
impairment_agg['Crash_Impairment_Category'] = impairment_agg['Max_Driver_Impairment_Severity'].map(final_risk_map_inverse)

data = data.merge(
    impairment_agg[['Crash_ID', 'Crash_Impairment_Category']],
    on='Crash_ID',
    how='left'
)

In [76]:
vehicle_factor =  pd.read_csv(r'C:\DATA ANALYSIS AND DATA SCIENCE PROJECTS\Accident Severity Prediction\data\raw data files\factor.csv')
print(vehicle_factor.columns)

vehicle_factor = vehicle_factor[['ST_CASE', 'VEHICLECCNAME']]
vehicle_factor.rename(columns={
    'ST_CASE': 'Crash_ID', 
    'VEHICLECCNAME': 'Vehicle_Contributing_Factor'
}, inplace=True) 

defect_risk_map = {
    # 1: Defect Found (High Risk)
    'Tires': 1, 'Brake System': 1, 'Steering': 1, 'Suspension': 1, 
    'Power Train': 1, 'Exhaust System': 1, 'Head Lights': 1, 
    'Signal Lights': 1, 'Other Lights': 1, 'Wipers': 1, 'Wheels': 1, 
    'Mirrors': 1, 'Windows/Windshield': 1, 'Body, Doors': 1, 
    'Truck Coupling/Trailer Hitch/Safety Chains': 1, 
    'Safety Systems': 1, 'Other': 1, 
    
    # 0: No Defect / Unknown (Low/No Risk)
    'None': 0, 'None Noted': 0,
    'Vehicle Contributing Factors - No Details': 0, 
    'Not Reported': 0, 'Unknown': 0, 'Reported as Unknown': 0,
}

vehicle_factor['Defect_Flag'] = vehicle_factor['Vehicle_Contributing_Factor'].map(defect_risk_map).fillna(0) 

vehicle_factor_agg = vehicle_factor.groupby('Crash_ID').agg(
    Crash_Vehicle_Defect_Max_Flag=('Defect_Flag', 'max')
).reset_index()

final_flag_map_inverse = {
    1: 'Yes',
    0: 'No'
}

vehicle_factor_agg['Crash_Vehicle_Defect'] = vehicle_factor_agg['Crash_Vehicle_Defect_Max_Flag'].map(final_flag_map_inverse).fillna('No')

data = data.merge(
    vehicle_factor_agg[['Crash_ID', 'Crash_Vehicle_Defect']],
    on='Crash_ID',
    how='left'
)

Index(['STATE', 'STATENAME', 'ST_CASE', 'VEH_NO', 'VEHICLECC',
       'VEHICLECCNAME'],
      dtype='object')

In [77]:
data.columns

Index(['State_Code', 'State_Name', 'Crash_ID', 'Count_Non_Motorists',
       'Count_Vehicles_Total', 'Count_Vehicle_Forms', 'Count_PVH_Involved',
       'Count_Occupants_MV', 'City_Name', 'Month_Name', 'Day_of_Month',
       'Day_of_Week', 'Crash_Hour', 'Crash_Minute', 'Area_Rural_Urban',
       'Road_Functional_Class', 'On_NHS_Road', 'Latitude', 'Longitude',
       'Intersection_Type', 'Light_Condition', 'Weather_Condition',
       'Notif_Hour', 'Notif_Minute', 'Arrival_Hour', 'Arrival_Minute',
       'Hospital_Hour', 'Hospital_Minute', 'Fatalities_Count',
       'Clean_Light_Condition', 'Clean_Weather_Condition', 'Total_Killed',
       'Total_Alive', 'Fatal_Seats_List', 'Killed_Restraint_List',
       'Any_Driver_Drinking', 'Total_Drinking_Drivers',
       'Driver_License_Category', 'Driver_Max_Prev_Accident_Count',
       'Driver_Max_Prev_Speeding_Count', 'Max_Driver_Age', 'Min_Driver_Age',
       'Driver_Sex_List', 'Total_Exceeding_Limit_Vehicles',
       'Total_Too_Fast_Vehicles', 'Max_Vehicle_Type_Severity_5',
       'Max_Vehicle_Damage_Rank', 'Max_Harmful_Event_Severity',
       'Crash_Road_Surface_Condition', 'Crash_Horizontal_Alignment',
       'Crash_Vertical_Profile', 'Crash_Impairment_Category',
       'Crash_Vehicle_Defect'],
      dtype='object')

In [78]:
final_column_order = [
    'Crash_ID', 'State_Code', 'State_Name', 'Total_Killed', 'Total_Alive', 'Fatalities_Count',
   
    'Area_Rural_Urban', 'Road_Functional_Class', 'On_NHS_Road', 'Intersection_Type', 
    'Latitude', 'Longitude', 'City_Name', 
    
    'Clean_Light_Condition', 'Clean_Weather_Condition', 'Crash_Road_Surface_Condition', 
    'Crash_Horizontal_Alignment', 'Crash_Vertical_Profile',
    
    'Crash_Impairment_Category', 'Any_Driver_Drinking', 'Total_Drinking_Drivers', 
    'Total_Exceeding_Limit_Vehicles', 'Total_Too_Fast_Vehicles', 'Crash_Vehicle_Defect',
    
    'Count_Vehicles_Total', 'Count_Occupants_MV', 'Count_Non_Motorists',
    'Max_Driver_Age', 'Min_Driver_Age', 'Driver_Sex_List', 'Driver_License_Category', 
    'Driver_Max_Prev_Accident_Count', 'Driver_Max_Prev_Speeding_Count',
    'Max_Harmful_Event_Severity', 'Max_Vehicle_Damage_Rank', 'Max_Vehicle_Type_Severity_5', 
    
    'Month_Name', 'Day_of_Week', 'Day_of_Month', 'Crash_Hour', 'Crash_Minute',
    'Notif_Hour', 'Notif_Minute', 'Arrival_Hour', 'Arrival_Minute', 'Hospital_Hour', 'Hospital_Minute'
]
total_killed_alive = total_killed_alive.reindex(columns=final_column_order)

In [79]:
data.isnull().sum()

State_Code                         0
State_Name                         0
Crash_ID                           0
Count_Non_Motorists                0
Count_Vehicles_Total               0
Count_Vehicle_Forms                0
Count_PVH_Involved                 0
Count_Occupants_MV                 0
City_Name                          0
Month_Name                         0
Day_of_Month                       0
Day_of_Week                        0
Crash_Hour                         0
Crash_Minute                       0
Area_Rural_Urban                   0
Road_Functional_Class              0
On_NHS_Road                        0
Latitude                           0
Longitude                          0
Intersection_Type                  0
Light_Condition                    0
Weather_Condition                  0
Notif_Hour                         0
Notif_Minute                       0
Arrival_Hour                       0
Arrival_Minute                     0
Hospital_Hour                      0
Hospital_Minute                    0
Fatalities_Count                   0
Clean_Light_Condition              0
Clean_Weather_Condition            0
Total_Killed                       0
Total_Alive                        0
Fatal_Seats_List                   0
Killed_Restraint_List              0
Any_Driver_Drinking                0
Total_Drinking_Drivers             0
Driver_License_Category           58
Driver_Max_Prev_Accident_Count    58
Driver_Max_Prev_Speeding_Count    58
Max_Driver_Age                    58
Min_Driver_Age                    58
Driver_Sex_List                   58
Total_Exceeding_Limit_Vehicles     0
Total_Too_Fast_Vehicles            0
Max_Vehicle_Type_Severity_5        0
Max_Vehicle_Damage_Rank            0
Max_Harmful_Event_Severity         0
Crash_Road_Surface_Condition       0
Crash_Horizontal_Alignment         0
Crash_Vertical_Profile             0
Crash_Impairment_Category          0
Crash_Vehicle_Defect               0
dtype: int64

In [80]:
import numpy as np
numerical_cols_to_impute = [
    'Driver_Max_Prev_Accident_Count', 
    'Driver_Max_Prev_Speeding_Count', 
    'Max_Driver_Age', 
    'Min_Driver_Age'
]

for col in numerical_cols_to_impute:
    median_val = data[col].median()
    data[col].fillna(median_val, inplace=True)

mode_license = data['Driver_License_Category'].mode()[0]
data['Driver_License_Category'].fillna(mode_license, inplace=True)

data['Driver_Sex_List'] = data['Driver_Sex_List'].astype(str)
data['Driver_Sex_List'].fillna('Other', inplace=True)
data['Driver_Sex_List'].replace('nan', 'Other', inplace=True)

C:\Users\Hp\AppData\Local\Temp\ipykernel_17660\2483694011.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[col].fillna(median_val, inplace=True)
C:\Users\Hp\AppData\Local\Temp\ipykernel_17660\2483694011.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Driver_License_Category'].fillna(mode_license, inplace=True)
C:\Users\Hp\AppData\Local\Temp\ipykernel_17660\2483694011.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Driver_Sex_List'].fillna('Other', inplace=True)
C:\Users\Hp\AppData\Local\Temp\ipykernel_17660\2483694011.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Driver_Sex_List'].replace('nan', 'Other', inplace=True)

In [82]:
data.isnull().sum()

State_Code                        0
State_Name                        0
Crash_ID                          0
Count_Non_Motorists               0
Count_Vehicles_Total              0
Count_Vehicle_Forms               0
Count_PVH_Involved                0
Count_Occupants_MV                0
City_Name                         0
Month_Name                        0
Day_of_Month                      0
Day_of_Week                       0
Crash_Hour                        0
Crash_Minute                      0
Area_Rural_Urban                  0
Road_Functional_Class             0
On_NHS_Road                       0
Latitude                          0
Longitude                         0
Intersection_Type                 0
Light_Condition                   0
Weather_Condition                 0
Notif_Hour                        0
Notif_Minute                      0
Arrival_Hour                      0
Arrival_Minute                    0
Hospital_Hour                     0
Hospital_Minute                   0
Fatalities_Count                  0
Clean_Light_Condition             0
Clean_Weather_Condition           0
Total_Killed                      0
Total_Alive                       0
Fatal_Seats_List                  0
Killed_Restraint_List             0
Any_Driver_Drinking               0
Total_Drinking_Drivers            0
Driver_License_Category           0
Driver_Max_Prev_Accident_Count    0
Driver_Max_Prev_Speeding_Count    0
Max_Driver_Age                    0
Min_Driver_Age                    0
Driver_Sex_List                   0
Total_Exceeding_Limit_Vehicles    0
Total_Too_Fast_Vehicles           0
Max_Vehicle_Type_Severity_5       0
Max_Vehicle_Damage_Rank           0
Max_Harmful_Event_Severity        0
Crash_Road_Surface_Condition      0
Crash_Horizontal_Alignment        0
Crash_Vertical_Profile            0
Crash_Impairment_Category         0
Crash_Vehicle_Defect              0
dtype: int64

In [81]:
data.to_csv('final_dataset.csv', index = 'False')